### ISSUE TITLE
list index out of range when using journey_map

### ISSUE THREAD

**Issue by shahargli** [time4tea/gopro-dashboard-overlay#103]
Hello,

When I try to add journey_map to a layout, gopro-dashboard.py fails with list index out of range.

>gopro-dashboard.py --layout-xml default-5312x2988.xml small3.mp4 out3.mp4
Starting gopro-dashboard version 0.85.0
    Timer(GPMD - Called: 1, Total: 0.00523, Avg: 0.00523, Rate: 191.17)
    Timer(extract GPS - Called: 1, Total: 0.02012, Avg: 0.02012, Rate: 49.71)
Request for data at time Timeunit ms=-8.694, before start of metadata, returning first item
    Timer(extract ACCL - Called: 1, Total: 0.10726, Avg: 0.10726, Rate: 9.32)
Request for data at time Timeunit ms=-8.694, before start of metadata, returning first item
    Timer(extract GRAV - Called: 1, Total: 0.06372, Avg: 0.06372, Rate: 15.69)
Request for data at time Timeunit ms=-8.694, before start of metadata, returning first item
    Timer(extract CORI - Called: 1, Total: 0.09897, Avg: 0.09897, Rate: 10.10)
Timer(parsing - Called: 1, Total: 0.29566, Avg: 0.29566, Rate: 3.38)
Note: 100 GoPro GPS readings were mapped to 'NO_LOCK', for the following reasons:
 DOP > 10 -> 100
Timer(loading timeseries - Called: 1, Total: 0.48200, Avg: 0.48200, Rate: 2.07)
Generating overlay at Dimension(x=5312, y=2988)
Timeseries has 100 data points
Processing....
Timer(processing - Called: 1, Total: 0.00120, Avg: 0.00120, Rate: 835.56)
FFMPEG Output is in /tmp/tmp4plcr8kr
Timelapse Factor = 0.988
Layout -> Include component 'date_and_time' = True
Layout -> Include component 'big_mph' = True
Layout -> Include component 'altitude' = True
Layout -> Include component 'journey_map' = True
Executing 'ffmpeg -y -hide_banner -loglevel info -i small3.mp4 -f rawvideo -framerate 10.0 -s 5312x2988 -pix_fmt rgba -i - -filter_complex [0:v][1:v]overlay -vcodec libx264 -preset veryfast out3.mp4'
Render: 0 [  0%]  [  0.0/s] |                                                                                                                                                                                               | ETA:  --:--:--Timer(image to bytes - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(writing to ffmpeg - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(drawing frames - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(program - Called: 1, Total: 0.56456, Avg: 0.56456, Rate: 1.77)
Traceback (most recent call last):
  File "/venv/bin/gopro-dashboard.py", line 329, in <module>
    frame = draw_timer.time(lambda: overlay.draw(dt))
  File "/venv/lib/python3.10/site-packages/gopro_overlay/timing.py", line 20, in time
    r = f()
  File "/venv/bin/gopro-dashboard.py", line 329, in <lambda>
    frame = draw_timer.time(lambda: overlay.draw(dt))
  File "/venv/lib/python3.10/site-packages/gopro_overlay/layout.py", line 106, in draw
    return self.scene.draw()
  File "/venv/lib/python3.10/site-packages/gopro_overlay/widgets/widgets.py", line 236, in draw
    w.draw(image, draw)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/widgets/widgets.py", line 32, in draw
    w.draw(image, draw)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/widgets/map.py", line 121, in draw
    self._init_maybe()
  File "/venv/lib/python3.10/site-packages/gopro_overlay/widgets/map.py", line 105, in _init_maybe
    plots = rdp(
  File "/venv/lib/python3.10/site-packages/gopro_overlay/rdp.py", line 66, in rdp
    results = [points[0], points[-1]]
IndexError: list index out of range
Render: 101 [100%]  [980.7/s] |#############################################################################################################################################################################################| Time:  0:00:00

The layout xml file contains:
\<component type="journey_map" name="journey_map" x="3260" y="700" size="512" corner_radius="35"/>

**Comment by time4tea** [comment]
Hi - This is the same issue as your other issue (although the error message is quite bad - I'll look at this)

```
Note: 100 GoPro GPS readings were mapped to 'NO_LOCK', for the following reasons:
DOP > 10 -> 100
Timeseries has 100 data points
```

All the GPS readings were filtered out because the readings were not accurate. See the information in the other issue for how to adjust this.

**Comment by time4tea** [comment]
Version 0.88.0 should address this issue (but you won't get any readings by default, as the GPS accuracy was too low) - see #102 for how to address this.
