### ISSUE TITLE
mpeg file too large?

### ISSUE THREAD

**Issue by shahargli** [time4tea/gopro-dashboard-overlay#104]
Hey,

Trying to create overlay for a large video file (14GB), gopro-dashboard.py fails with timeout:

>/venv/bin/gopro-dashboard.py --layout-xml default-5312x2988.xml --gps-dop-max 30 --gps-speed-max 150 --gps-speed-max-units knots output.mp4 output_overlay.mp4
Starting gopro-dashboard version 0.88.0
Traceback (most recent call last):
  File "/venv/bin/gopro-dashboard.py", line 192, in <module>
    frame_meta = framemeta_from(
  File "/venv/lib/python3.10/site-packages/gopro_overlay/framemeta.py", line 339, in framemeta_from
    gpmd_from = load_gpmd_from(filepath)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 204, in load_gpmd_from
    result = run(cmd, capture_output=True, timeout=10)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/process.py", line 5, in run
    return subprocess.run(cmd, check=True, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2006, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.10/subprocess.py", line 1198, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['ffmpeg', '-hide_banner', '-y', '-i', PosixPath('output.mp4'), '-codec', 'copy', '-map', '0:2', '-f', 'rawvideo', '-']' timed out after 10 seconds
output.mp4 appears to be located on a slow device. Please ensure both input and output files are on fast disks
Timer(loading timeseries - Called: 1, Total: 10.40891, Avg: 10.40891, Rate: 0.10)
Timer(program - Called: 1, Total: 10.40900, Avg: 10.40900, Rate: 0.10)

**Comment by time4tea** [comment]
hiya - as the message says - the files seem to be on slow disks? - what kind of disks are the files on? Drives connected by USB are not suitable really.

**Comment by time4tea** [comment]
Can you try this please:
`time ffmpeg -hide_banner -y -i output.mp4 -codec copy -map 0:2 -f rawvideo - > /dev/null 2>&1`

On my computer this returns:
```
real	0m0.126s
user	0m0.340s
sys	0m0.212s
```

when run against a 12G file.

**Comment by shahargli** [comment]
sure:

>time ffmpeg -hide_banner -y -i output.mp4 -codec copy -map 0:2 -f rawvideo - > /dev/null 2>&1
>real    0m0.407s
user    0m0.067s
sys     0m0.067s

>bash-5.1# ls -l output.mp4
-rw-r--r--    1 root     root     13820330877 Feb  5 15:33 output.mp4

**Comment by shahargli** [comment]
After restarting the container, did another, exact same, run of gopro-dashboard.py with the same file, no timeout and gopro-dashboard.py is creating the output file.
