### ISSUE TITLE
It is not straightforward to use HW acceleration on macs when creating gpx-only overlays

### ISSUE THREAD

**Issue by KarolisL** [time4tea/gopro-dashboard-overlay#109]
It was pretty easy to create a png-based dashboard following [docs](https://github.com/time4tea/gopro-dashboard-overlay/tree/main/docs/bin#creating-videos-using-only-gpx-file), but 2h gpx results in 20GiB+ file.

I wasn't able to make `hevc_videotoolbox` work:

```json
 {
   "overlay-apple": {
      "input": [],
      "output": ["-vcodec", "hevc_videotoolbox", "-q:v", "65"]
  }
}
```

fails without a clear error.

I was able to use `h264_videotoolbox` to render the dashboard fast-ish enough, which results in ~1Gi file:

```json
{
  "overlay-apple": {
    "input": ["-hwaccel", "videotoolbox"],
    "output": ["-vcodec", "h264_videotoolbox", "-q:v", "65"]
  }
}
```

Given the [contributing guidelines](https://github.com/time4tea/gopro-dashboard-overlay/blob/main/CONTRIBUTING.md#pull-requests), I ask for permission to raise a PR to expand the docs.

**Comment by time4tea** [comment]
To include Macs with some hardware acceleration would be great. Please do send some changes. Thank you!
