### ISSUE TITLE
OSError: Component of type 'gps_lock_icon' is not recognized.

### ISSUE THREAD

**Issue by YouthfulRicker** [time4tea/gopro-dashboard-overlay#115]
After executing this command:
`gopro-dashboard.py --layout xml --layout-xml ~/Downloads/gopro-dashboard-overlay-main/gopro_overlay/layouts/default-1920x1080.xml GH010111.MP4 GH010111-dash.MP4`

I get this result after a short while:
`OSError: Component of type of 'gps_lock_icon' is not recognised, check spelling / examples`

Surprisingly i haven't seen this error before, so I can't be more exact about what it could be, sorry!

**Comment by time4tea** [comment]
Hi. From the command line you used, it looks like you installed it in some unusual way. Perhaps you checked it out of git?

I suspect the version of the program and the config have fallen out of sync, on your computer.

The best way to ensure this doesn't happen is to use the packaged software and install with pip.

```
python3 -m venv venv 
venv/bin/pip install gopro-overlay
```

**Comment by YouthfulRicker** [comment]
Ah yeah thanks, sorry should've rechecked the README again, however after doing that I now get an error indicating that pip hasn't got the `gopro_overlay.counter` python library:
```  
 File "/Users/[me]/opt/miniconda3/bin/gopro-dashboard.py", line 14, in <module>
    from gopro_overlay.counter import ReasonCounter
ModuleNotFoundError: No module named 'gopro_overlay.counter'
```

**Comment by time4tea** [comment]
> Ah yeah thanks, sorry should've rechecked the README again, however after doing that I now get an error indicating that pip hasn't got the `gopro_overlay.counter` python library:
> ```  
>  File "/Users/[me]/opt/miniconda3/bin/gopro-dashboard.py", line 14, in <module>
>     from gopro_overlay.counter import ReasonCounter
> ModuleNotFoundError: No module named 'gopro_overlay.counter'
> ```


Looks like you are not running the program as advised... it is picking up the program from
"/opt/miniconda..."

The instructions suggest to run as 

venv/bin/gopro-dashboard.py ...

Give that a try...

**Comment by YouthfulRicker** [comment]
I am now getting this:
```
Traceback (most recent call last):
  File "/Users/antariksh/venv/bin/gopro-dashboard.py", line 22, in <module>
    from gopro_overlay.layout_xml import layout_from_xml, load_xml_layout
  File "/Users/antariksh/venv/bin/gopro_overlay/layout_xml.py", line 326, in <module>
    @pint.register_unit_format("c")
AttributeError: module 'pint' has no attribute 'register_unit_format'
```

when I run this;
```
venv/bin/gopro-dashboard.py Documents/temp/GH010111.MP4 Documents/temp/GH010111-dash.MP4
```

**Comment by time4tea** [comment]
Please just start with an empty folder, if there is `venv` in it, delete it.
Run the following commands:
```
python3 -mvenv venv
venv/bin/pip install gopro-overlay
venv/bin/gopro-dashboard.py 
```
You need to be using python3.10.

Hope that helps

**Comment by YouthfulRicker** [comment]
Ok, done that, sorry but now this is happening:
```
Starting gopro-dashboard version 0.79.0
    Timer(GPMD - Called: 1, Total: 4.52527, Avg: 4.52527, Rate: 0.22)
    Timer(extract GPS - Called: 1, Total: 3.33529, Avg: 3.33529, Rate: 0.30)
    Timer(extract ACCL - Called: 1, Total: 7.27747, Avg: 7.27747, Rate: 0.14)
Request for data at time Timeunit ms=-67.233, before start of metadata, returning first item
    Timer(extract GRAV - Called: 1, Total: 2.32722, Avg: 2.32722, Rate: 0.43)
Request for data at time Timeunit ms=-67.233, before start of metadata, returning first item
    Timer(extract CORI - Called: 1, Total: 3.39066, Avg: 3.39066, Rate: 0.29)
Timer(parsing - Called: 1, Total: 20.85718, Avg: 20.85718, Rate: 0.05)
Timer(loading timeseries - Called: 1, Total: 23.64968, Avg: 23.64968, Rate: 0.04)
Timer(program - Called: 1, Total: 23.64976, Avg: 23.64976, Rate: 0.04)
Traceback (most recent call last):
  File "/Users/antariksh/venv/bin/gopro-dashboard.py", line 177, in <module>
    if counter.total() > 0:
AttributeError: 'ReasonCounter' object has no attribute 'total'
```

**Comment by time4tea** [comment]
You are using an older version of python.

**Comment by YouthfulRicker** [comment]
I am using Python version 3.9.12 as indicated by the pyvenv.cfg file though

**Comment by time4tea** [comment]
I don't know what that file is. 

In the README requirements it says Python3.10.

https://github.com/time4tea/gopro-dashboard-overlay/blob/main/README.md#requirements

**Comment by YouthfulRicker** [comment]
Ok, It's working now thanks!, and sorry for the disruption.

**Comment by time4tea** [comment]
No worries - I hope the program is useful for you! - The easiest way to make sure it works is just to follow the installation instructions - this will ensure that all the library versions are correct, and don't clash with other installed software on your computer.
I should add a python version check, as currently the "ReasonCounter" error message is not very helpful.
Cheers!
