### ISSUE TITLE
struct.error: unpack from requires a buffer

### ISSUE THREAD

**Issue by YouthfulRicker** [time4tea/gopro-dashboard-overlay#116]
After running this command:
`venv/bin/gopro-dashboard.py --map-style geo-klokantech-basic --map-api-key [censored-api-key]  --layout xml --layout-xml /Users/antariksh/.gopro-graphics/layouts/default-3840x2160-1080scaled\ copy Documents/temp/GH010112.MP4 Documents/temp/GH010112-dash.MP4`

I get this output:
```
Starting gopro-dashboard version 0.90.0
    Timer(GPMD - Called: 1, Total: 0.62938, Avg: 0.62938, Rate: 1.59)
Timer(parsing - Called: 1, Total: 0.62992, Avg: 0.62992, Rate: 1.59)
Timer(loading timeseries - Called: 1, Total: 1.81826, Avg: 1.81826, Rate: 0.55)
Timer(program - Called: 1, Total: 1.81829, Avg: 1.81829, Rate: 0.55)
Traceback (most recent call last):
  File "/Users/antariksh/venv/bin/gopro-dashboard.py", line 192, in <module>
    frame_meta = framemeta_from(
                 ^^^^^^^^^^^^^^^
  File "/Users/antariksh/venv/lib/python3.11/site-packages/gopro_overlay/framemeta.py", line 340, in framemeta_from
    return parse_gopro(gpmd_from, units, metameta, gps_lock_filter=gps_lock_filter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antariksh/venv/lib/python3.11/site-packages/gopro_overlay/framemeta.py", line 309, in parse_gopro
    gopro_meta = GoproMeta.parse(gpmd_from)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antariksh/venv/lib/python3.11/site-packages/gopro_overlay/gpmd.py", line 317, in parse
    return GoproMeta(list(GPMDParser(data).items()))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antariksh/venv/lib/python3.11/site-packages/gopro_overlay/gpmd.py", line 261, in items
    item = self.from_array(self.data, offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/antariksh/venv/lib/python3.11/site-packages/gopro_overlay/gpmd.py", line 266, in from_array
    fourcc, type_char_code, size, repeat = GPMDStruct.unpack_from(data, offset=offset)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack_from requires a buffer of at least 2464288 bytes for unpacking 8 bytes at offset 2464280 (actual buffer size is 2464284)
```
I'm using a mac, and i installed said program in a generic venv with python3.11 and pip3.11. I've tried without custom maps and custom xmls, neither fixed the issue.

**Comment by time4tea** [comment]
Hi, Thanks for reporting the issue. I can say I've never seen this error. 
I've not tried running with python3.11, although I can't imagine that would have any effect.
Would you be able to send me the source video? You can use wetransfer to send it to gopro-overlay [at] time4tea.net
If you don't want to, that's of course totally OK.

James

**Comment by YouthfulRicker** [comment]
I would, but it's over two gigs, sorry.

**Comment by time4tea** [comment]
OK, no worries. Could you try running `gopro-extract.py` on the video, and then send me the output. This will hopefully extract only the gopro data from the video. It will be much smaller.
Hopefully the program will work, it doesn't get much use!

**Comment by YouthfulRicker** [comment]
done

**Comment by time4tea** [comment]
Hiya - Having taken a look at the file, I can see it is corrupted. The file from a HERO 10 Black has a data error at the end - it looks like the sort of thing that might happen if the SD card was failing.
I'm not sure what to do with this to be honest - writing code that can continue after receiving corrupt data is quite a bit more effort - as you never know where the data corruption will be - it could be while reading any value.
The file ends with an incomplete data structure, with a type of `b'\x00\x11\xa3\x10'` - this is not a valid type.
My instinct is to not "fix" this - to allow the successful parsing of corrupt data - but to perhaps enhance the error message.
