### ISSUE TITLE
gopro-cut failed while working on gopro 10 video

### ISSUE THREAD

**Issue by shahargli** [time4tea/gopro-dashboard-overlay#119]
Hello,

Tried to cut a gopro 10 video, and failed: "Error initializing output stream 0:2"
> /venv/bin/gopro-cut.py --start 00:00:00 --duration 00:00:10 /work/GX010028.MP4 /work/GX010028_cut.mpg

> ['ffmpeg', '-hide_banner', '-y', '-i', '/work/GX010028.MP4', '-map_metadata', '0', '-map', '0:0', '-map', '0:1', '-map', '0:3', '-copy_unknown', '-ss', '0.0', '-t', '10.0', '-c', 'copy', '/work/GX010028_cut.mpg']
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/work/GX010028.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2023-02-16T09:23:36.000000Z
    location        : +32.5945+035.2360/
    location-eng    : +32.5945+035.2360/
    firmware        : H21.01.01.50.00
  Duration: 00:15:00.91, start: 0.000000, bitrate: 35559 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 35301 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2023-02-16T09:23:36.000000Z
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      encoder         : GoPro H.265 encoder
      timecode        : 09:23:02:23
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2023-02-16T09:23:36.000000Z
      handler_name    : GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 09:23:02:23
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2023-02-16T09:23:36.000000Z
      handler_name    : GoPro TCD
      timecode        : 09:23:02:23
  Stream #0:3[0x4](eng): Data: bin_data (gpmd / 0x646D7067), 53 kb/s (default)
    Metadata:
      creation_time   : 2023-02-16T09:23:36.000000Z
      handler_name    : GoPro MET
[mpeg @ 0x7fd1afcb1ac0] VBV buffer size not set, using default size of 230KB
If you want the mpeg file to be compliant to some specification
Like DVD, VCD or others, make sure you set the correct buffer size
[mpeg @ 0x7fd1afcb1ac0] Unsupported audio codec. Must be one of mp1, mp2, mp3, 16-bit pcm_dvd, pcm_s16be, ac3 or dts.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:2 --
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:3 -> #0:2 (copy)
    Last message repeated 1 times
Traceback (most recent call last):
  File "/venv/bin/gopro-cut.py", line 51, in <module>
    cut_file(args.input, args.output, from_seconds, duration)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 80, in cut_file
    run(args)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/process.py", line 5, in run
    return subprocess.run(cmd, check=True, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-hide_banner', '-y', '-i', '/work/GX010028.MP4', '-map_metadata', '0', '-map', '0:0', '-map', '0:1', '-map', '0:3', '-copy_unknown', '-ss', '0.0', '-t', '10.0', '-c', 'copy', '/work/GX010028_cut.mpg']' returned non-zero exit status 1.

**Comment by time4tea** [comment]
Hi - I think this is complaining (in a non-user-friendly way) that you cannot write a video movie into an audio file. '.mpg' is an mpeg audio file. try writing to a .mp4 file, and see how you get on.

**Comment by shahargli** [comment]
yes, issue solved!
thanks a lot!
