### ISSUE TITLE
Support for older Gopro camers (i.e. Hero 5)

### ISSUE THREAD

**Issue by FFMbyBicycle** [time4tea/gopro-dashboard-overlay#129]
Currently only newer recordings are supported as the older ones use a different file naming. I didn't want to rename my video (series), so I made [a few small fixes and added more regex voodoo in filenaming.py](https://github.com/FFMbyBicycle/gopro-dashboard-overlay/commit/d4b894d12a9babf1c688fba4fa5b1ccba55f0c2f) to add support for the older file naming scheme (see lower part here: https://community.gopro.com/t5/en/GoPro-Camera-File-Naming-Convention/ta-p/390220 ) while keeping newer ones working.

Do you want me to add a PR for this? I tried to understand the tests, but I'm not that deep into Python and failed at that step. It would be really nice if we could add that support for everybody :+1:

**Comment by time4tea** [comment]
hiya - thanks for the suggestion and code -  this is only used in the `gopro-rename` program - you should be able to to use `gopro-dashboard` unchanged.... is that your intention?

**Comment by FFMbyBicycle** [comment]
Sorry, I may have to be more precise: I tried to use [gopro-join, which also uses the code](https://github.com/time4tea/gopro-dashboard-overlay/blob/main/bin/gopro-join.py#L8) and it failed to work with older Gopro videos. That's why I added the fix. gopro-dashboard itself worked fine as far as I remember.

**Comment by time4tea** [comment]
ok - so 0.96.0 should have this fix. I can't really test it with real data, but please let me know how it goes. It might take a few minuted to show up in PyPI.

**Comment by FFMbyBicycle** [comment]
Thanks! It seems to work for most cases, which is fine for me :+1:
