### ISSUE TITLE
error with newest version

### ISSUE THREAD

**Issue by KyleGW** [time4tea/gopro-dashboard-overlay#13]
Not sure what's going on, at first I thought it was something with my local copy, but still seeing an issue after refreshing everything. Something with the import of layouts, line 19 in layout_xml.py. So I stopped trying to use a custom layout or a non-default map, and still seeing it. see screenshot. 

The recent updates with custom layouts are awesome.
![Screenshot 2022-02-01 221053](https://user-images.githubusercontent.com/9725098/152091890-f01ee579-5562-44ce-9010-1b6e290fd42d.jpg)

**Comment by time4tea** [comment]
Confirmed on 0.16.0

**Comment by time4tea** [comment]
Sadly 0.17.0 doesn't quite fix this either. Its a packaging problem... working on it.

**Comment by time4tea** [comment]
0.18.0 should fix this. Thanks for bringing it to my attention. There are now a number of tests on the pypi distribution so this shouldn't happen again.

**Comment by KyleGW** [comment]
one final fix needed - line 154 in gopro-dashboard.py
change args.layout to args.layout_xml

Example:
From:
    overlay = Overlay(timeseries,
                              create_desired_layout(
                                  args.layout,
                                  args.include, args.exclude,
                                  renderer, timeseries, font, privacy_zone)
to:
overlay = Overlay(timeseries,
                              create_desired_layout(
                                  args.layout_xml,
                                  args.include, args.exclude,
                                  renderer, timeseries, font, privacy_zone)

**Comment by time4tea** [comment]
oops. ok hopefully that has really fixed it this time. I'll put some more end-to-end tests in so this doesn't happen again. thanks for your timely feedback.

**Comment by KyleGW** [comment]
No problem - thanks for the quick work on the fixes.

**Comment by time4tea** [comment]
This should now be fixed :crossed_fingers:
