### ISSUE TITLE
5k video is freezing after running gopro-dashboard

### ISSUE THREAD

**Issue by Charmik** [time4tea/gopro-dashboard-overlay#134]
Hello! I am trying to process my video from go-pro 11. Just to be sure I made 2 changes:
1) I use another font because there is no Roboto-Medium.ttf on my m1-Mac. I will commit this separately to this issue.
2) I created default-5312x2988.xml because it's resolution of my video. I mostly copy-pasted everything from default-3840x2160.xml, but Right now I just commented everything so I have `empty` html  file.

The problem is after processing I get video and it works okay, but sometimes it freezes for a second or two. It happens a few times for 2 mins video. I use video from go-pro & gpx file from garmin.connect (I can share both files if you want to debug the problem - please let me know and I will upload it somewhere). 
Or if you have any thoughts what I can try to change - tell me:) 

Source video is okay of course, I checked. 

I tried to change arguments for ffmpeg in ffmpeg.py (like framerate, -preset flag and everything I thought could be related to the problem) - no impact so far. Sometimes things were even worse.

my command line looks like that: `gopro-dashboard.py --gpx /Users/alovkov/Downloads/activity_11244613820.gpx /Users/alovkov/Downloads/GX010046.MP4 /Users/alovkov/Downloads/output.MP4`

and the ffmpeg command: `Executing ffmpeg -y -hide_banner -loglevel info -i /Users/alovkov/Downloads/GX010046.MP4 -f rawvideo -framerate 10.0 -s 5312x2988 -pix_fmt rgba -i - -filter_complex [0:v][1:v]overlay -vcodec libx264 -preset veryfast /Users/alovkov/Downloads/output.MP4`

(I just found your project and it's fascinating! I hope we can fix this problem and I will be your user) :) 
Thanks a lot!

**Comment by time4tea** [comment]
Hey. Thanks for taking the time to report the problem. Hopefully we can get to the bottom of it.

Firstly, easy one - you can specify the font on the command line with `--font xxx`

Secondly, the command line looks OK. It shouldn't freeze! I don't have a mac or Windows machine,.so the testing is limited/none on those platforms but people have said it works fine on both those platforms in the past.

First question is how it was installed? Did you create special `venv` as in the installation instructions? Sometimes people run it from a git clone and this could cause some issues. Lastly, please could you share the output from the program when this happens?

Thank you! Hopefully we can get to the bottom of the issue.

James

**Comment by Charmik** [comment]
Thanks for fast response! Earlier I ran it in PyCharm - but tried terminal with venv the result is the same. 
1) I did from your doc: 
`
python -m venv venv
venv/bin/pip install gopro-overlay
`
2) Sorry I am not a python dev, so silly question: now I have vevn but it doesn't contain my local changes (I suppose I got vevn like from master?). There is not changes in gopro-dashboard.py and I have master's layout. So I just did this: 

`cp gopro_overlay/layouts/default-5312x2988.xml venv/lib/python3.11/site-packages/gopro_overlay/layouts`
It seems weird, but yeah... how should I do it properly? 

then I ran: 
`venv/bin/gopro-dashboard.py --font NewYork.ttf --gpx /Users/alovkov/Downloads/activity_11244613820.gpx /Users/alovkov/Downloads/GX010046.MP4 /Users/alovkov/Downloads/output.MP4`

Video is still freezing. output: 
```
➜  gopro-dashboard-overlay git:(main) ✗ venv/bin/gopro-dashboard.py --font NewYork.ttf --gpx /Users/alovkov/Downloads/activity_11244613820.gpx /Users/alovkov/Downloads/GX010046.MP4 /Users/alovkov/Downloads/output.MP4
Starting gopro-dashboard version 0.98.0
ffmpeg version is 6.0
Using Python version 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
    Timer(GPMD - Called: 1, Total: 0.02437, Avg: 0.02437, Rate: 41.03)
    Timer(extract GPS - Called: 1, Total: 0.06132, Avg: 0.06132, Rate: 16.31)
    Timer(extract ACCL - Called: 1, Total: 0.38069, Avg: 0.38069, Rate: 2.63)
    Timer(extract GRAV - Called: 1, Total: 0.12022, Avg: 0.12022, Rate: 8.32)
    Timer(extract CORI - Called: 1, Total: 0.21363, Avg: 0.21363, Rate: 4.68)
Timer(parsing - Called: 1, Total: 0.80044, Avg: 0.80044, Rate: 1.25)


NOTE: 30 GoPro GPS readings were mapped to 'NO_LOCK', for the following reasons:
* DOP > 10 -> 30



GPX/FIT Timeseries has 1312 data points.. merging...
Timer(loading timeseries - Called: 1, Total: 1.24254, Avg: 1.24254, Rate: 0.80)
Generating overlay at Dimension(x=5312, y=2988)
Timeseries has 1596 data points
Processing....
Timer(processing - Called: 1, Total: 0.21475, Avg: 0.21475, Rate: 4.66)
FFMPEG Output is in /var/folders/43/bf88p74d7p5_vyh771w2v8080000gn/T/tmpo1qlqjum
Timelapse Factor = 1.002
Executing 'ffmpeg -y -hide_banner -loglevel info -i /Users/alovkov/Downloads/GX010046.MP4 -f rawvideo -framerate 10.0 -s 5312x2988 -pix_fmt rgba -i - -filter_complex [0:v][1:v]overlay -vcodec libx264 -preset veryfast /Users/alovkov/Downloads/output.MP4'
Render: 0 [  0%]  [  0.0/s] |                                                                                                                                                                                                                                  | ETA:  --:--:--Request for data at time Timeunit ms=0.0, before start of metadata, returning first item
Render: 1596 [ 99%]  [  3.9/s] |############################################################################################################################################################################################################################## | ETA:   0:00:00Finished drawing frames. waiting for ffmpeg to catch up
Render: 1597 [100%]  [  3.8/s] |###############################################################################################################################################################################################################################| Time:  0:06:57
Timer(drawing frames - Called: 1,597, Total: 414.05772, Avg: 0.25927, Rate: 3.86)
Timer(program - Called: 1, Total: 419.21512, Avg: 419.21512, Rate: 0.00)
```

**Comment by time4tea** [comment]
To reference a custom layout you can save the layout file anywhere on your computer and use:
`venv/bin/gopro-dashboard.py --layout-xml /path/to/layout.xml ....`

I can see there it says "finished drawing frames" - this implies to me that it completed ok? 
Is it the program that is freezing or the generated video?
Can you play the original video without any problem? 
In the output you can see "FFMPEG output is in /var......" - please could you attach that file or send it to me?

It might be good if you can share the video and gpx file with me. You can send via Wetransfer or similar to gopro-overlay [at] time4tea.net - but of course no worries if not.

Cheers!

James

**Comment by Charmik** [comment]
Yes, the program finished okay and I get a result video...but it freezes (generated video is freezing in a few moments). Original video is okay as I said in the first message. 

I send you original video & gpx file by Wetransfer. Please tell me if you didn't get it. 

output or var file:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/alovkov/Downloads/GX010046.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2023-06-01T09:30:26.000000Z
    location        : +34.7046+033.1131/
    location-eng    : +34.7046+033.1131/
    firmware        : H22.01.02.10.00
  Duration: 00:02:39.66, start: 0.000000, bitrate: 60089 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 5312x2988 [SAR 1:1 DAR 16:9], 59826 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2023-06-01T09:30:26.000000Z
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      encoder         : GoPro H.265 encoder
      timecode        : 12:29:41:06
    Side data:
      displaymatrix: rotation of -180.00 degrees
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2023-06-01T09:30:26.000000Z
      handler_name    : GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 12:29:41:06
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2023-06-01T09:30:26.000000Z
      handler_name    : GoPro TCD
      timecode        : 12:29:41:06
  Stream #0:3[0x4](eng): Data: bin_data (gpmd / 0x646D7067), 57 kb/s (default)
    Metadata:
      creation_time   : 2023-06-01T09:30:26.000000Z
      handler_name    : GoPro MET
Input #1, rawvideo, from 'fd:':
  Duration: N/A, start: 0.000000, bitrate: 5079121 kb/s
  Stream #1:0: Video: rawvideo (RGBA / 0x41424752), rgba, 5312x2988, 5079121 kb/s, 10 tbr, 10 tbn
Stream mapping:
  Stream #0:0 (hevc) -> overlay (graph 0)
  Stream #1:0 (rawvideo) -> overlay (graph 0)
  overlay:default (graph 0) -> Stream #0:0 (libx264)
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
[libx264 @ 0x12a8053b0] using SAR=1/1
[libx264 @ 0x12a8053b0] using cpu capabilities: ARMv8 NEON
[libx264 @ 0x12a8053b0] profile High, level 6.0, 4:2:0, 8-bit
[libx264 @ 0x12a8053b0] 264 - core 164 r3095 baee400 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=15 lookahead_threads=5 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/Users/alovkov/Downloads/output.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    firmware        : H22.01.02.10.00
    location        : +34.7046+033.1131/
    location-eng    : +34.7046+033.1131/
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 5312x2988 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 30k tbn
    Metadata:
      encoder         : Lavc60.3.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2023-06-01T09:30:26.000000Z
      handler_name    : GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 12:29:41:06
      encoder         : Lavc60.3.100 aac
[rawvideo @ 0x12aa05f60] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
frame= 4785 fps= 11 q=-1.0 Lsize= 1968854kB time=00:02:39.61 bitrate=101047.8kbits/s speed=0.382x
video:1966180kB audio:2502kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.008750%
[libx264 @ 0x12a8053b0] frame I:42    Avg QP:23.66  size:954475
[libx264 @ 0x12a8053b0] frame P:1289  Avg QP:26.19  size:540734
[libx264 @ 0x12a8053b0] frame B:3454  Avg QP:27.11  size:369506
[libx264 @ 0x12a8053b0] consecutive B-frames:  2.7%  2.3%  2.9% 92.1%
[libx264 @ 0x12a8053b0] mb I  I16..4: 11.1% 43.1% 45.8%
[libx264 @ 0x12a8053b0] mb P  I16..4: 14.2% 44.7% 13.0%  P16..4: 10.8%  8.6%  5.5%  0.0%  0.0%    skip: 3.1%
[libx264 @ 0x12a8053b0] mb B  I16..4:  7.2% 27.0%  6.6%  B16..8: 20.2% 10.5%  1.3%  direct: 5.5%  skip:21.7%  L0:43.7% L1:38.4% BI:17.9%
[libx264 @ 0x12a8053b0] 8x8 transform intra:64.2% inter:43.0%
[libx264 @ 0x12a8053b0] coded y,uvDC,uvAC intra: 68.2% 13.7% 1.7% inter: 24.0% 9.2% 0.1%
[libx264 @ 0x12a8053b0] i16 v,h,dc,p: 39% 23% 26% 12%
[libx264 @ 0x12a8053b0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 16% 18% 23%  4% 10%  6%  7%  6%  9%
[libx264 @ 0x12a8053b0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 17% 19% 14%  4% 13%  8%  8%  7%  9%
[libx264 @ 0x12a8053b0] i8c dc,h,v,p: 71% 15% 13%  1%
[libx264 @ 0x12a8053b0] Weighted P-Frames: Y:1.6% UV:0.5%
[libx264 @ 0x12a8053b0] kb/s:100883.07
[aac @ 0x12a8064f0] Qavg: 1123.714
```

**Comment by time4tea** [comment]
Thanks for sending your files -... just downloading them now..

**Comment by time4tea** [comment]
hi - so a few things i notice... 5k videos are still pretty hi-res I think - there are relatively few devices on the market that can play them at native resolution.

I tried playing your original video - it doesn't play properly in VLC - you get a blue image. ffmpeg can't process it in hardwards using my RTX3060 as it only supports up to 4096 pixel frames.

I tried to create a movie using gopro-dashboard on top of your movie, and it also didn't work.... I just got an error "no playable streams" when using ffmpeg 4.4.2.

Using ffmpeg 6.0 however, everything worked as expected... although I still cannot play it in VLC - perhaps the version of VLC I have doesn't like that encoding/frame size/bit rate?

I can see that you're using ffmpeg6.0 - can you try some other video player and see if you get different results? it seems that to play 5.7k videos you need to be at the bleeding edge of video processing software.

I don't think that this is a bug with gopro-overlay itself, but perhaps in order to process and play 5.7k there are some minimum versions of supporting software that are required?

Not quite sure how to proceed with this at the moment...

**Comment by time4tea** [comment]
I had exactly the same results with a 5k video i made with my own GoPro Hero 11, so I don't think yours is faulty.

**Comment by Charmik** [comment]
Hey! I use QuickTime Player on my mac. I tried VLC - it works okay too. I don't have any blud image... 

A funny thing happened: I tried it again and it works...no lags! but I downloaded video from go-pro again because I cleared my Downloads... seems weird. 

if I have lags in the future can you recommend doing something before dashboard? to reformat it to 2k maybe or something like that...? I just bought it so not sure...I just use default settings for now:)
