### ISSUE TITLE
cleanup temporary files

### ISSUE THREAD

**Issue by blshkv** [time4tea/gopro-dashboard-overlay#135]
version 0.92.0
after running the following command:
```gopro-dashboard.py --video-time-end file-modified --use-gpx-only --gpx ./Afternoon_Ride.gpx --layout-xml ./layout.xml  ./20230614175306_00822.MP4 ./20230614175306_00822_out2.MP4```
it were the following two files left over in my system:
/tmp/{tmpqaxw5ryg, tmpt2f2c4es}

Please make sure that all  temporary files are removed

**Comment by time4tea** [comment]
Hi. Thanks for using the software and taking time to report a defect. 
This is not a priority.

**Comment by blshkv** [comment]
https://github.com/time4tea/gopro-dashboard-overlay/blob/main/gopro_overlay/common.py#L24

[You need to](https://docs.python.org/3/library/tempfile.html)
```
[mkstemp()](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) and [mkdtemp()](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp) are lower-level functions which require manual cleanup.```

So basically you either need to use a high level function (with delete=True option), or add a specific code to delete the file.
