### ISSUE TITLE
time data does not match format

### ISSUE THREAD

**Issue by CaptFreezer** [time4tea/gopro-dashboard-overlay#141]
Hello,

first of all, thanks for this great tool, it helps alot to get GPS Data from my GoPro :)
but, one of my last videos are a bit strange.
I have 4 seperate files, and the 3rd one is throwing this error message:
`ValueError: time data '5509100082240400' does not match format '%y%m%d%H%M%S.%f'`
when i am using gopro-dashboard.py for the other 3 videos it renders fine, but that 3rd video is very strange, and i don't know what the problem could be..
i have read, that this number 5509100082240400 could be a GPS-DateTime value? 
When i am using this cmdline
`exiftool GH030037.MP4 -ee -G3 -sampletime -gpsdatetime`
everything seems to be ok and working.. correct date and time values.. example: 
```
[Doc1]          GPS Date Time                   : 2023:06:25 11:17:50.284
[Doc2]          GPS Date Time                   : 2023:06:25 11:17:50.284
[Doc3]          GPS Date Time                   : 2023:06:25 11:17:52.374
[Doc4]          GPS Date Time                   : 2023:06:25 11:17:52.374
[Doc5]          GPS Date Time                   : 2023:06:25 11:17:52.374
[Doc6]          GPS Date Time                   : 2023:06:25 11:17:55.784
[Doc7]          GPS Date Time                   : 2023:06:25 11:17:56.554
[Doc8]          GPS Date Time                   : 2023:06:25 11:17:58.039
...
```
If you need something for me to test or something else, i can help you with that.

Regards

**Comment by time4tea** [comment]
Hi - Thanks for your interest. This is something that has been reported one time before - that the GoPro is recording invalid datetime values in its datastream. It was previously reported in #22 
I also raised it as an issue against the GoPro itself. - https://github.com/gopro/gpmf-parser/issues/162  - but nobody was able to reliably reproduce the problem. It is possible that its a filesystem corruption issue,or a defect in the GoPro firmware.
Out of curiosity, what type of GoPro didd the recording?

**Comment by time4tea** [comment]
Hi @CaptFreezer - would you be able to share your mp4 file with me?

It will be used only for diagnostic reasons.

If you can, and please don't feel obliged, please send a link to gopro-overlay@time4tea.net

I find that wetransfer can be good for this.

Thanks!

James

**Comment by CaptFreezer** [comment]
My GoPro 9 Hero Black did the recording. The strange thing is, out of those 4 files, only the 3rd file has this issue.
I can share this video, when i am at home. Any sites you prefer to upload/download/share the file?

**Comment by time4tea** [comment]
Thank you for the info. If the file is 2GB or less, then wetransfer can be good. 

If your file is bigger than this, we'll have to find an alternative...

Let know at gopro-overlay@time4tea.net 

Thanks!

**Comment by CaptFreezer** [comment]
I think it will be 4GB, but i will see, when i am at home (at around 5:30 PM MESZ)

**Comment by time4tea** [comment]
Hi thanks for the file - I can definitely see that there are two dodgy timestamps in the file.... however actually the GPS chip was misbehaving throughout, and there is very little usable information in the file. I have seen this one time before, and there's not much I can do with the file unfortunately. I would suggest a factory reset, and upgrading to the latest firmware if this isn't already the latest version.

**Comment by time4tea** [comment]
By the way I love the video - If you can find a still frame that you don't mind sharing, I'd love to add it to the gallery.

**Comment by time4tea** [comment]
It seems that whatever this bug in the GoPro firmware is, it won't be fixed. Maybe I'll try to find a way to workaround it.

**Comment by CaptFreezer** [comment]
Thanks for the information. :)
If you can find a workaround, it will be nice. :)
If you want the map and speed thing in action, you can use this video: https://www.youtube.com/watch?v=S-Hf78bHOjY

**Comment by time4tea** [comment]
There is a workaround for this in 0.124.0 - Should be available in PyPI very soon.
