### ISSUE TITLE
Is there any way to display custom data?

### ISSUE THREAD

**Issue by xiaoxin01** [time4tea/gopro-dashboard-overlay#148]
I've success displaying the power data on the video, but I can't find a way to change some value and display, for example, I want to display the power-to-body ratio(w/kg), which takes the value of power divided by weight.

Is there any way to display the power-to-body ratio?

**Comment by time4tea** [comment]
Currently there isn't any support for computed values, however it shouldn't be too hard to add some fixed ones.

Thanks for the suggestion!

**Comment by CyrilSLi** [comment]
I have added support to display custom GPX extensions (for each point) and metadata (for the whole file), currently only as text, using `metric="custom_fields"` and `metric="custom_metadata"` respectively with `format` being the index. This can be useful for an external application to insert computed values. I will write some docs over the next couple of days and submit a PR.

Fork: [https://github.com/CyrilSLi/gopro-dashboard-overlay](https://github.com/CyrilSLi/gopro-dashboard-overlay)
