### ISSUE TITLE
FFMPEG Profile configuration Not Found 

### ISSUE THREAD

**Issue by SlippyJimmy** [time4tea/gopro-dashboard-overlay#152]
when I `Create a movie with alpha channel, using only GPX file, without any video at all`,and run `docker run -it -v "$(pwd):/work" overlaydash/gopro-dashboard-overlay:latest gopro-dashboard.py --use-gpx-only --gpx sample-data.gpx --profile overlay --overlay-size 1920x1080 GH020073-dashboard.mov`,there are `ValueError: Expecting to find an FFMPEG Profile configuration at: /root/.gopro-graphics/ffmpeg-profiles.json`.but i have created this file in project path and home path.

OS:MacOS13.6Ventura

Docker Image:v0.105.0

**Comment by SlippyJimmy** [comment]
What is the correct `root` directory

**Comment by time4tea** [comment]
Hi, Thanks for your interest in the software.

Using docker, while allowing to get started easily, makes a couple of things more complicated as the configuration files that are normally located in your home directory are not accessible to the program running in docker.

The two routes available to you are:

- Creating and mapping ~/.gopro-graphics into the docker container.

- Using additional flags to the program to set the location of cache and configuration locations.

I'll add another comment with exact usage for these two cases.


Or... install the program without docker. This is my recommendation for more complex use cases - like custom profiles.


I think that perhaps I could bundle some popular profiles with the software, meaning that users won't have to edit them... but this won't fix your immediate issue.

**Comment by time4tea** [comment]
Hi @SlippyJimmy - did you manage to get it to work? If you did, please do post your solution, it would be very helpful!

Thanks! James
