### ISSUE TITLE
Attribute Error when Evaluating GoPro and GPX File Overlap

### ISSUE THREAD

**Issue by IbnGit** [time4tea/gopro-dashboard-overlay#154]
Hi there -

It's been long while, but I've been using your code for quite some time now. We exchanged emails a while back about time lapses.

Anyway, I've updated to the latest code recently and I seem to be getting this error whenever I am using GoPro and GPX data to create overlays.  This was not the case in the past. As best as I can tell, my issue is with DateRange.overlap_seconds.  Specifically, it's the 2nd time it's called (~line 236) and it's that the function is trying to do something with two different types of variables: frame_meta is Timeunit (I think) while fit_or_gpx_timeseries's is datetime.datetime.

I'm not sure if this is just me, but I can't see any other open or closed issues related to this...so hopefully just a user error??

Thanks!

<img width="1246" alt="Screenshot 2023-10-23 at 9 06 03 PM" src="https://github.com/time4tea/gopro-dashboard-overlay/assets/56657090/f738211f-427e-4812-9b01-155a31582c5e">

**Comment by time4tea** [comment]
Hi there - thanks for reporting this. I'll look into it....

**Comment by time4tea** [comment]
This should be fixed in 0.108.0 which will be on PyPI in a few moments.

**Comment by IbnGit** [comment]
Worked for me! Thank you.

**Comment by time4tea** [comment]
Thank you very much for reporting!
