### ISSUE TITLE
Pace Convert Error

### ISSUE THREAD

**Issue by SlippyJimmy** [time4tea/gopro-dashboard-overlay#156]
`ZeroDivisionError: float division by zero`
<img width="1421" alt="image" src="https://github.com/time4tea/gopro-dashboard-overlay/assets/45062658/57304e90-64b1-4129-80de-0e8bc3ef9c0c">

**Comment by time4tea** [comment]
Doh - sorry that is an obvious thing to miss.

**Comment by time4tea** [comment]
I am fixing this.. sorry been slightly unwell! - found a few other issues with pace too, like we didn't have a way to format the numbers like "2:17" etc... fix coming very soon.

**Comment by time4tea** [comment]
This should be better in v0.110.0 -> which should be visible on PyPi very soon.

**Comment by SlippyJimmy** [comment]
<img width="115" alt="image" src="https://github.com/time4tea/gopro-dashboard-overlay/assets/45062658/8b7fc0c5-ab1b-4b70-9ffc-5c24b2c41254">
1. Second's value should be 1-60.
2. Use colon instead of period between minute and second.

**Comment by time4tea** [comment]
The pace doesn't auto format you can try format="pace"

https://github.com/time4tea/gopro-dashboard-overlay/tree/main/docs/xml/examples/04-metrics#pace

Hopefully that will work...

**Comment by time4tea** [comment]
Hi @SlippyJimmy were the fixes OK for you?

**Comment by SlippyJimmy** [comment]
> Hi @SlippyJimmy were the fixes OK for you?

The pace function can be used normally, but the value does not display in the first five seconds. Can this be fixed?
