### ISSUE TITLE
Enhancement idea: Map widget that shows a zoomed in version of the track

### ISSUE THREAD

**Issue by KyleGW** [time4tea/gopro-dashboard-overlay#16]
This would be kind of a combination of the moving map and the journey map. A journey map, where the level of zoom is configurable, which shows that zoomed in view of the track as the video moves along the track.

I am currently achieving this by splitting the video into small chunks, rendering the dashboard to it so that the journey map has a zoomed in view, and then stitching them all back together again.  

I guess this would also be like taking the moving map, drawing a track on it, and not having it rotate like it does by default. So a possible implementation would be to add options to the moving map widget to draw the track on the moving map, and a configurable flag to turn off the rotation.

**Comment by time4tea** [comment]
New component "moving journey map" introduced in 0.37.0 - please take a look.

**Comment by time4tea** [comment]
I hope that this component suits your use case. I'm not really a fan of just closing things unless they are confirmed to be resolved, but also don't want to leave issues open for ages... please just get in touch...

**Comment by KyleGW** [comment]
New moving journey map widget working great and solved the need. Thank you!
