### ISSUE TITLE
Support GPUs

### ISSUE THREAD

**Issue by tve** [time4tea/gopro-dashboard-overlay#18]
I have an nvidia gpu and using it to decode & encode the video does provide some noticeable speed-up. I tested this using a hack:
```
diff --git a/gopro_overlay/ffmpeg.py b/gopro_overlay/ffmpeg.py
index a26829c..13bb160 100644
--- a/gopro_overlay/ffmpeg.py
+++ b/gopro_overlay/ffmpeg.py
@@ -178,18 +178,20 @@ class FFMPEGOverlay:
             filter_extra = f",scale=-1:{self.vsize}"
         cmd = [
             "ffmpeg",
-            "-y",
+            "-y", "-hide_banner",
             "-loglevel", "info",
+            "-hwaccel", "nvdec",
             "-i", self.input,
             "-f", "rawvideo",
             "-framerate", "10.0",
             "-s", f"{self.overlay_size.x}x{self.overlay_size.y}",
             "-pix_fmt", "rgba",
             "-i", "-",
             "-r", "30",
             "-filter_complex", f"[0:v][1:v]overlay{filter_extra}",
-            "-vcodec", "libx264",
-            "-preset", "veryfast",
+            "-vcodec", "h264_nvenc", "-rc:v", "cbr", "-b:v", "50000k", "-bf:v", "3", "-profile:v",
"high", "-spatial-aq", "true",
+            #"-vcodec", "libx264",
+            #"-preset", "veryfast",
             self.output
         ]
```
What I've seen done in some other projects is to provide a commandline option to override the encoder options and another to override the decoder options. This avoids trying to figure out the best options for all the permutations out there. The docs can then provide some suggestions for different GPUs. (I don't claim mine above to be ideal, I'm getting a 60MB data rate from my hero 7 and these settings preserve that more or less.)

**Comment by time4tea** [comment]
Thanks for the information about ffmpeg parameters for gpus!

**Comment by tve** [comment]
I'm seeing the same in terms of performance improvement ;-)

**Comment by time4tea** [comment]
Closing this - i think the current feature set supports GPS now.
