### ISSUE TITLE
Please add cmdline option for frame rate

### ISSUE THREAD

**Issue by tve** [time4tea/gopro-dashboard-overlay#19]
I'm recording at 60fps and currently the ffmpeg commands have 30fps hard-coded (`-r 30`), please provide an option to specify 60fps.

**Comment by time4tea** [comment]
Thanks for the info. As with #18 ... need to figure out a way to support various ffmpeg output controls...

**Comment by time4tea** [comment]
This was changed in 1d53e34d to just use the input file framerate. hopefully this is 'good enough' for now. have to have a think about how to make it work for more comprehensive control over fmmpeg options - there are too many to build them all in (as I think you suggested elsewhere)

**Comment by time4tea** [comment]
Closing this - profiles feature can be used to set output framerate. See docs for more details.
