### ISSUE TITLE
When Creating Videos using only GPX File,How to use GPU

### ISSUE THREAD

**Issue by ZeluEee** [time4tea/gopro-dashboard-overlay#195]

**Comment by time4tea** [comment]
Hiya, thanks for your interest in the software.

You should be able to  use `--profile nvgpu` if you have an nvidia gpu.

Various combinations are documented at https://github.com/time4tea/gopro-dashboard-overlay/tree/main/docs/bin

What did you try? What results did you get?

**Comment by ZeluEee** [comment]
Thanks,Solved my problem
