### ISSUE TITLE
Data extraction error - GOPRO Hero 10

### ISSUE THREAD

**Issue by jmootrey** [time4tea/gopro-dashboard-overlay#201]
There seems to be an issue with the latest version of GoPro firmware on the Hero10 and several telemetry applications, including gopro-dashboard-overlay.  Data extraction is giving bad results. Log output indication suspicious GPS packets, related to issue 141. I do not believe this to be the case.  https://goprotelemetryextractor.com/free/ can successfully read and parse data. 

Parsing via https://goprotelemetryextractor.com/free/
[telemeteylight.csv](https://github.com/user-attachments/files/16354909/telemeteylight.csv)

Parsing via gopro-dashboard-overlay
[gopro-dashboard-overlay.csv](https://github.com/user-attachments/files/16354913/gopro-dashboard-overlay.csv)

Happy to provide file via wetransfer.

**Comment by jmootrey** [comment]
Operator error.

**Comment by time4tea** [comment]
No worries. Glad you sorted it out!

James
