### ISSUE TITLE
(f***g) german umlauts in layout file

### ISSUE THREAD

**Issue by RalfPeter** [time4tea/gopro-dashboard-overlay#206]
Hi, 
i just found your very interesting project and tried to change an layout file. First Problem i got were german umlauts. I wanted to name the 'ALT' into german word 'Höhe'. As you can see i have a special sign inside. 
In the resulting video i got some special sign, but not the german umlaut. The layout file is coded in utf-8.
Pleas can you give me an advice?
TY

**Comment by RalfPeter** [comment]
I found it myself. I have to use unicode encodinf: ä = &#228; (html encoding &auml; is not working!).

**Comment by time4tea** [comment]
Ah, I am glad about this. XML files must be processed in utf-8 or utf-16 so this sort of thing "should just work".
