### ISSUE TITLE
How are GPX files used?

### ISSUE THREAD

**Issue by tve** [time4tea/gopro-dashboard-overlay#21]
What does gopro-dashboard do with GPX data? I was hoping it would use the GPS data in the gopro file to pick data from the GPX file, i.e., synchronize the two. But it seems it just blindly assumes the video and GPX files are perfectly synchronized and completely discards the GPS data in the MP4?

**Comment by time4tea** [comment]
Good question. Currently it uses the GPS date from the video to find the matching section from the gpx file, and then uses the gpx data in preference to the gopro data. 
This is a known area for enhancement...

**Comment by time4tea** [comment]
This has changed quite a bit in new version 0.40.0. Please see if this makes some kind of improvement
