### ISSUE TITLE
Problem with transparency.

### ISSUE THREAD

**Issue by chabapj** [time4tea/gopro-dashboard-overlay#210]
The only way I can get the transparent overlay, for use in e.g. DaVinci Resolve, is to encode it as png. Everything else comes with a black background. Am I doing something wrong? I tried various pixel formats. Using png is okay, but the files are huge.

**Comment by victorlysak** [comment]
qtrle ?
like in your ffmpeg-profiles.json would be:

```
{
    "speed-elev": {
      "input": ["-hwaccel", "auto"],
      "output": ["-r", "50", "-vcodec", "qtrle", "-pix_fmt", "argb" ]
    },
    "map": {
      "input": ["-hwaccel", "auto"],
      "output": ["-r", "50", "-vcodec", "qtrle", "-pix_fmt", "argb"]
    }
}

```

**Comment by chabapj** [comment]
Thanks - I never tried this codec. I will check it.

**Comment by chabapj** [comment]
It is ~50% of the PNG size. Thank you!

**Comment by time4tea** [comment]
This is amazing! Never heard of it! Thanks!

**Comment by victorlysak** [comment]
I've never used vlc. Always and only mpv.
Vlc for me in Linux always nightmare to watch.

**Comment by chabapj** [comment]
It looks great in mpv.

**Comment by time4tea** [comment]
added to docs. thanks @victorlysak
