### ISSUE TITLE
Fails to run... potential ffmpeg setup issue??

### ISSUE THREAD

**Issue by fahrsoft** [time4tea/gopro-dashboard-overlay#25]
I have installed this under the virtual environment "goprodash" and downloaded ffmpeg and ffprobe 4.4.1 from https://ffbinaries.com/downloads. I put those into the ./goprodash/bin/ directory and made them executable. Then I had to run them to grant them access to run on my Mac. Now, when I run the dashboard, I get the following:

```
(goprodash) tonylmiller@Drinian ~ % ./goprodash/bin/gopro-dashboard.py ~/Downloads/GOPR6228.mov ~/Downloads/GOPR6228Ovr.mp4
Traceback (most recent call last):
  File "/Users/tonylmiller/./goprodash/bin/gopro-dashboard.py", line 80, in <module>
    stream_info = find_streams(input_file)
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 77, in find_streams
    ffprobe_output = str(invoke(["ffprobe", "-hide_banner", filepath]).stderr)
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 19, in invoke
    return run(cmd, **kwargs, stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding="UTF-8")
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 14, in run
    return subprocess.run(cmd, check=True, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1149, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 2042, in _communicate
    stderr = self._translate_newlines(stderr,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1026, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 325: invalid continuation byte
```

If I don't drop the ffmpeg stuff in like this, I get "Can't start ffmpeg - is it installed?" If there's a more appropriate way to install ffmpeg let me know and I'll try it.

**Comment by time4tea** [comment]
I dont have access so its a bit hard to test.

Normally you'd install ffmpeg somewhere in the search path, and it would "just work". This is probably fine.

This looks like an encoding issue with the output from ffprobe.

Can you attach the output of `ffprobe -hide_banner movie.mp4` (replacing movie.mp4 with the path to your movie!)

Cheers

**Comment by time4tea** [comment]
This may be fixed in [v0.30.0](https://github.com/time4tea/gopro-dashboard-overlay/releases/tag/v0.30.0) - please try installing again / updating and see if this makes a difference. I had to make an untested change, as I don't have a Mac to test on.

**Comment by fahrsoft** [comment]
Did a full reinstall and still having an error. 
`(goprodash) tonylmiller@Drinian bin % ~/goprodash/bin/gopro-dashboard.py ~/Downloads/GP026230.mov ~/Downloads/GP026230ovr.mov    
Traceback (most recent call last):
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 19, in invoke
    return run(cmd, **kwargs, text=True, capture_output=True)
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 14, in run
    return subprocess.run(cmd, check=True, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-hide_banner', '/Users/tonylmiller/Downloads/GP026230.mov']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tonylmiller/goprodash/bin/gopro-dashboard.py", line 83, in <module>
    stream_info = find_streams(input_file)
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 77, in find_streams
    ffprobe_output = str(invoke(["ffprobe", "-hide_banner", filepath]).stderr)
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 21, in invoke
    raise IOError(f"Error: {cmd}\n stdout: {e.stdout}\n stderr: {e.stderr}")
OSError: Error: ['ffprobe', '-hide_banner', '/Users/tonylmiller/Downloads/GP026230.mov']
 stdout: 
 stderr: Output #0, mov, to '/Users/tonylmiller/Downloads/GP026230.mov':
Output file #0 does not contain any stream
`

**Comment by time4tea** [comment]
Ah, OK. Well that has fixed the character encoding issue then.
So, there seems to be an issue with the gopro file, maybe with the file, or maybe with the interpretation of the file..

Can you run from the terminal:

`ffprobe /Users/tonylmiller/Downloads/GP026230.mov`

and then attach the output. Thanks!

**Comment by time4tea** [comment]
I'm a bit confused, as according to the gopro docs, no gopro files have the extension .mov

https://community.gopro.com/s/article/GoPro-Camera-File-Naming-Convention?language=en_US

Are you definitely using the original file from the gopro, and not something that has been edited or created with Quik or other editing software. Just trying to guess what might be up...

**Comment by fahrsoft** [comment]
Hmmm.... it's after importing them into the iMovie library. I didn't think that was modifying them, just copying them over into the directory structure. I'll grab something directly and see if that's got something to do with it. 
Here's the ffprobe output... certainly looks like an issue with the file. 
```
(goprodash) tonylmiller@Drinian bin % ./ffprobe ~/Downloads/GP026230.mov 
ffmpeg version 4.4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Output #0, mov, to '/Users/tonylmiller/Downloads/GP026230.mov':
Output file #0 does not contain any stream
```

**Comment by fahrsoft** [comment]
iMovie does seem to rename the file (so much for "originals"), but direct from the GoPro results in the same output:
```
(goprodash) tonylmiller@Drinian bin % ./ffprobe ~/Downloads/GP026230.MP4 
ffmpeg version 4.4.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Output #0, mp4, to '/Users/tonylmiller/Downloads/GP026230.MP4':
Output file #0 does not contain any stream
```

**Comment by time4tea** [comment]
Hmm. It's hard to say, but either your version of ffmpeg/ffprobe doesn't contain the right extensions to be able to understand the file format, or the file that you have copied isn't the direct file from the gopro, or the gopro you are using isn't creating the files or metadata correctly. 
My guess would be that the file you have copied isn't quite the right file, but it's hard to be sure.
Can you play the file using a media player?

**Comment by fahrsoft** [comment]
The second file (the MP4) is directly from the GoPro (5 black, if I remember right). They both play with media players on the machine.

**Comment by fahrsoft** [comment]
Perhaps there's something about how ffmpeg is installed... not all the libraries, not in the path, something like that that I'm not getting right or is different from your setup??? How should I be installing that?

**Comment by time4tea** [comment]
I dont have a mac, so everything is different... so I don't really know, I'm sorry. 

The first step to getting this working will be to install ffmpeg so that it can understand your gopro file.

Perhaps you could try homebrew install instead?

Once that is working, I suspect you'll have much more luck. Sorry can't be of more use.

**Comment by fahrsoft** [comment]
I've done the Homebrew installation of ffmpeg and that does seem like it did a lot more than the download of the executable. Before launching into the virtual environment or anything, I ran ffmpeg and ffprobe on the file and got much the same answer from ffmpeg, but I don't know if the ffprobe result helps with its "unsupported codec" error:
```
tonylmiller@Drinian ~ % ffprobe ~/Downloads/GOPR6180.MP4                                                                                        
ffprobe version 5.0 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.30)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/5.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/tonylmiller/Downloads/GOPR6180.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2021-11-25T13:06:06.000000Z
    firmware        : HD5.02.02.70.00
  Duration: 00:00:21.46, start: 0.000000, bitrate: 60135 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 2704x1520 [SAR 1:1 DAR 169:95], 59959 kb/s, 59.94 fps, 59.94 tbr, 60k tbn (default)
    Metadata:
      creation_time   : 2021-11-25T13:06:06.000000Z
      handler_name    :         GoPro AVC
      vendor_id       : [0][0][0][0]
      encoder         : GoPro AVC encoder
      timecode        : 13:05:19:19
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2021-11-25T13:06:06.000000Z
      handler_name    :         GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 13:05:19:19
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2021-11-25T13:06:06.000000Z
      handler_name    :         GoPro TCD
      timecode        : 13:05:19:19
  Stream #0:3[0x4](eng): Data: bin_data (gpmd / 0x646D7067), 38 kb/s (default)
    Metadata:
      creation_time   : 2021-11-25T13:06:06.000000Z
      handler_name    :         GoPro MET
  Stream #0:4[0x5](eng): Data: none (fdsc / 0x63736466), 13 kb/s (default)
    Metadata:
      creation_time   : 2021-11-25T13:06:06.000000Z
      handler_name    :         GoPro SOS
Unsupported codec with id 0 for input stream 2
Unsupported codec with id 98314 for input stream 3
Unsupported codec with id 0 for input stream 4

```
I appreciate the effort your putting into all of this!!!

**Comment by fahrsoft** [comment]
One last update tonight. I pulled a new file directly from the GoPro (and included the .LRV and .THM files just in case they are required) and now that I've done the different installation of ffmpeg, I get a different error... so that's maybe encouraging. Is it possible that the data streams are different on my older GoPro than what you're testing with?
```
(goprodash) tonylmiller@Drinian ~ % ./goprodash/bin/gopro-dashboard.py ~/Downloads/GOPR6229.MP4 ~/Downloads/GOPR6229ovr.MP4                                               
Traceback (most recent call last):
  File "/Users/tonylmiller/./goprodash/bin/gopro-dashboard.py", line 83, in <module>
    stream_info = find_streams(input_file)
  File "/Users/tonylmiller/goprodash/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 101, in find_streams
    raise IOError("Invalid File? The data stream doesn't seem to contain GoPro audio, video & metadata ")
OSError: Invalid File? The data stream doesn't seem to contain GoPro audio, video & metadata 
```

**Comment by tve** [comment]
I'm seeing the same ffprobe output (OK, I haven't compared char by char) and the same 3 unsupported code warnings, but gopro-overlay works fine (although on Linux and no virtual env). Are you sure when you run gopro-overlay that it doesn't pick-up ffmpeg from the virtual env, i.e., have you removed that (incomplete) installation?
(@time4tea I fear you need some more detailed error messages for this case 'cause this is bound not to be the last problematic ffmpeg install situation...)

**Comment by time4tea** [comment]
This may be fixed now again, in a different way, by using the JSON output of ffprobe - as in #29

**Comment by time4tea** [comment]
I'm going to close this, as I think its fixed. Please do open another issue if there's still a problem.
