### ISSUE TITLE
GPS time synchronization can be way off

### ISSUE THREAD

**Issue by tve** [time4tea/gopro-dashboard-overlay#32]
I've been working on a 1-1/2 hour video and after getting it to run through gopro-dashboard without error I'm finding that the overlay and video are not at all in sync. Off by many seconds, i.e. completely unusable.

I tracked down the issue to be GPS initialization: the first video file (i.e. GH01xxx.MP4) has the typical 31860 frames covering 531.531 seconds but the GPMD track only has 4729 data points covering 334.247 seconds. By using gopro-to-csv I can see that it skips a ton of GPS points because it doesn't have a fix.

I looked a bit into the GPMD format and I'm not getting a clear picture of how one has to get time information. One thing is sure, the primary time sync between video and gpmd data comes from MP4 and that is lost when doing the raw dump using ffmpeg. There is a TSMP (timestamp) item in the GPMD stream, but I can't tell from the Gopro docs what it really counts, i.e., whether it can be used on its own to keep video frames and metadata in sync.

I'm trying out a different way to do gopro-dashboard in order to fix the time sync issue and to support multiple disjoint video snippets:
- accept a list of input files, which will be concatenated in the output
- for each file, determine the start time using the first valid GPS fix in gpmd
- calculate the number of overlay frames as exactly as possible
- concatenate the info into a `video_timeseries`, which is the time-points at which overlay data is needed (really just the `date` portion of `Timeseries`)
- accept or produce a `trip_timeseries` (from provided GPX file or from the GPMD data), to be used as source for overlay data
- produce overview widgets (such as trip map) from `trip_timeseries` so they show the full trip/event, not just what's in the video snippets
- produce "momentary" widgets also from the `trip_timeseries`, using the `video_timeseries` time-points and interpolating from `trip_timeseries`

The biggest issue I have left to resolve is how to determine the exact start-time of a video file. It's easy to find the first GPS record that has a good fix and thus time, but I'm not sure yet how to figure out which video frame that corresponds to (or equivalently, how many milliseconds into the video it is).

**Comment by time4tea** [comment]
Yes - this is a bit of a problem at the moment. The program assumes that the GPS is locked at the start. This is a wrong assumption sometimes. 
I *think* that we have enough information to reconstruct the frame number from the information we have already (given that there will be a DEVC block every frame (mostly) , and we know from ffprobe that the  frame rate is 60000/1001 (or whatever)) , but making it all sync properly is a bit tricky, and I haven't had an opportunity to sit down and make it work properly.
you'll have to use the the GPSU items to attach known times to frames, then interpolate / extrapolate forwards and backwards to fill in those times where they are not known.

**Comment by tve** [comment]
Tada!
```
> ffprobe -hide_banner -select_streams 3 -print_format json -show_packets -show_data GH010279.MP4
{
    "packets": [
        {
            "codec_type": "data",
            "stream_index": 3,
            "pts": 0,
            "pts_time": "0.000000",
            "dts": 0,
            "dts_time": "0.000000",
            "duration": 1001,
            "duration_time": "1.001000",
            "size": "4040",
            "pos": "15302049",
            "flags": "K_",
            "data": "\n00000000: 4445 5643 0001 0fc0 4456 4944 4c04 0001  DEVC....DVIDL...\n00000010
: 0000 0001 4456 4e4d 6301 000b 4865 726f  ....DVNMc...Hero\n00000020: 3720 426c 6163 6b00 5354 524d
 0001 04d4  7 Black.STRM....\n00000030: 5453 4d50 4c04 0001 0000 00b7 5354 4e4d  TSMPL.......STNM\n0
0000040: 6301 000e 4163 6365 6c65 726f 6d65 7465  c...Acceleromete\n00000050: 7200 0000 5349 554e 63
04 0001 6d2f 73b2  r...SIUNc...m/s.\n00000060: 5343 414c 7302 0001 01a2 0000 4d54 5258  SCALs.......
MTRX\n00000070: 6624 0001 0000 0000 0000 0000 3f80 0000  f$..........?...\n00000080: 0000 0000 bf80
0000 0000 0000 3f80 0000  ............?...\n00000090: 0000 0000 0000 0000 4f52 494e 6301 0003  .....
...ORINc...\n000000a0: 5978 5a00 4f52 494f 6301 0003 5a58 5900  YxZ.ORIOc...ZXY.\n000000b0: 4143 434
c 7306 00b7 0e9b 02a7 087f 0e73  ACCLs..........s\n000000c0: 02c3 086b 0e17 02ff 0877 0ddb 02f3 083b
  ...k.....w.....;\n000000d0: 0d83 035b 080f 0d7f 0363 0823 0d5b 0337  ...[.....c.#.[.7\n000000e0: 0
887 0d67 033f 089f 0d4f 0323 0893 0d4b  ...g.?...O.#...K\n000000f0: 033b 086f 0d1f 0347 086f 0cf3 03
1f 0873  .;.o...G.o.....s\n00000100: 0d13 030f 087f 0d73 030f 07ef 0dc3 02eb  .......s........\n0000
0110: 07bb 0deb 02d3 07ab 0dfb 02db 07b3 0de3  ................\n00000120: 0327 07c3 0e0f 0317 07a3
...
```
Requires some hex parsing, but hey, that's easy... An alternative might be to read the MP4 directly, e.g. using https://github.com/beardypig/pymp4 but I'm a bit concerned about how complex deducing time information might end up being (not familiar with MP4 format details).

**Comment by tve** [comment]
Implementation in https://github.com/tve/gopro-dashboard-overlay gopro-dash2
Main piece: https://github.com/tve/gopro-dashboard-overlay/commit/8e94e2f9b7ed2e9484d922340bcaf6db60512c00
Doesn't concatenate multiple files yet...

**Comment by tve** [comment]
Well, this is a mess....

Recording 1 consisting of 10 files (531.531 seconds each, except last):
- GPS locked 192 seconds into 1st file
- GPS time advances in sync with MP4 timestamps through 1st file
- metadata track in file 1 ends ~5 seconds before the end of the file
- the last timestamp in file 1 and the first timestamp in file 2 "match up" (the expected approx 1s delta)
- the video is indeed 531.531 seconds long, i.e., it's not that the end of the file got chopped off
- conclusion: the metadata track is somehow shifted ART the video

Recording 2 consisting of 15 files:
- GPS was locked at the start
- file 3 has 531.531s of video but 532.532s of metadata
- file 4 "catches up" again in that it has 531.531s of video but only 530.53s of metadata
- files 6 and 7 repeat the same "one second of metadata in the wrong file" pattern

**Comment by time4tea** [comment]
Are you able to share the video file (recording 1) with me? Of course its ok if you don't want to for whatever reason. It would help though in understanding the specific problems you have. I am looking at a better way to parse the metadata, to sync up with the the video, but i've just not much time. I'm going to see if i can take a look now though. Initial experiments seem to show that it is much better, but i don't have many examples where there is 'odd' data.
if you can, send a link to gopro-overlay (at) time4tea (dot.) net.

**Comment by tve** [comment]
I'll upload some of the videos, it just takes a long time due to upload bandwidth constraints..
I noticed that the first frame of the GPMD track for "Recording 1, file 1" is as follows:
```
[PACKET]                                                                                             [0/49628]
codec_type=data
stream_index=3
pts=0
pts_time=0.000000
dts=0
dts_time=0.000000
duration=1001
duration_time=1.001000
size=4248
pos=7867500
flags=K_
[/PACKET]
```
Noteworthy is the "pos", which is an offset into the file, and "pts" being zero. This means "pts" is relative to the start of the track, and the start of the track is a ways into the file. So it seems to me that in order to sync the tracks one has to really parse the tracks in the MP4 file, follow their timestamps, and the figure out where they start relative to one-another.

I tried using `ffprobe -show_packets` to get the full packet info for a file, but after a while it only prints info for stream 4, so I'm suspecting some limitation/bug in there. :-(

NB: this discussion seems relevant, haven't fully grok'ed it yet, though: https://github.com/gopro/gpmf-parser/issues/90#issuecomment-719770933

**Comment by tve** [comment]
I do not believe https://github.com/gopro/gpmf-parser/issues/90#issuecomment-719770933 is useful, there is nothing in the GPMF stream that allows sync with the video, one has to use the MP4 timestamps. https://github.com/gopro/gpmf-parser/issues/36#issuecomment-418449253 (and some other issue responses there) indicate that once sync is established one can count on it, and that the +/-1 metadata frame per file mentioned for 'recording 2' above is expected.

So I believe the algorithm needs to be:
- Follow video and metadata frames in the MP4 stream until the first metadata frame is found, establish `gpmf_start_offset`
- Follow the metadata frames until the second gpmf frame with a GPS timestamp is found, establish `gps_lock_offset` from start of metadata track, the second gpmf frame is used because the very first GPS timestamp could be anywhere in the gpmf frame, which has a duration of ~1 second
- Calculate the start time of the video as `gps_time - gps_lock_offset - gpmf_start_offset`
- Thereafter expect video and gpmf to remain in sync within the same recording session based on filename matching
- The expected sync accuracy is ~0.15s, this could perhaps be improved by finding the GPMF frame with the smallest offset between frame start and GPS timestamp

**Comment by time4tea** [comment]
Ah. Thanks for pointing these comments out.... I think perhaps a penny is starting to drop in my mind about how this stuff works...  I think this links up with some of the code in the C demo.

**Comment by time4tea** [comment]
I have been looking at some footage I took with hero 9, and the sync looks way better using the approach in the linked footage. Taking the timestamp of the first SHUT, and using that to sync the other metadata is looking good. However, in the hero 7 footage you sent, the SHUT frame has no timestamp, and I dont know if the GPS5 packets do either yet, so thats the next thing to look at. However this does feel like progress!

**Comment by time4tea** [comment]
continuation files, where metadata for the one video frame is potentially in a different file, may well be a rhing too, but sorting out this issue should help identify those cases.

**Comment by time4tea** [comment]
Using some code I don't understand, I can now get the same frame offsets for the GoPro 7 files as the demo code in the GoPro repo. I need to plug that into the GPS parsing so that it can use either timestamps or the calculated stuff. 
here are some partially implemented things...
https://github.com/time4tea/gopro-dashboard-overlay/blob/frame-based-metadata/tests/test_framedata.py
https://github.com/time4tea/gopro-dashboard-overlay/blob/ee4de2a122a009a9b0dfa3a62f29c34a218d86f0/gopro_overlay/framemeta.py#L113

**Comment by time4tea** [comment]
I've implemented the sync estimation function and clarified that this only works correctly with older cameras ( gopro/gpmf-parser#155 ) , so next thing is to plug it all together. The work is happening in the https://github.com/time4tea/gopro-dashboard-overlay/tree/frame-based-metadata branch. It sort of works with "new" camera footage, but not yet with older.

**Comment by time4tea** [comment]
Please try new version 0.40.0

**Comment by time4tea** [comment]
I am going to close this issue as I believe that it is fixed. Please do open another issue against > 0.40.0 if there are problems, as the sync code is way different now.
