### ISSUE TITLE
Possible additional tool: extract metadata

### ISSUE THREAD

**Issue by gregbaker** [time4tea/gopro-dashboard-overlay#33]
This is certainly a departure from the purpose of this package, but I was trying to extract raw data from a GoPro video, and the infrastructure here got me there. If this would be useful to anyone else, you're welcome to it.

The `bin/gopro-data-extract.py` command in [my fork](https://github.com/gregbaker/gopro-dashboard-overlay) will extract a specific field from the metadata and dump it to a newline-delimited JSON file.
```bash
python gopro-data-extract.py -f GYRO GH010000.MP4 gyro.ndjson
python gopro-data-extract.py -f ACCL GH010000.MP4 accl.ndjson
python gopro-to-csv.py GH010000.MP4 gps.csv
```

The ndjson output is a little unusual, I admit, but it was easy to produce and can be read in Apache Spark or in Pandas with `pd.read_json(file, lines=True, convert_dates=['timestamp'])`.

Note: my code doesn't do the `CorrectionFactorsPacketTimeCalculator` or `CoriTimestampPacketTimeCalculator` corrections to the timestamps.

**Comment by time4tea** [comment]
Nice 👍
We're you thinking to merge this into main? I think that would be fine...

**Comment by gregbaker** [comment]
I'm happy if you'd like to merge it. I can do a PR if that's easiest

**Comment by time4tea** [comment]
Commits are now in main, and have been released. Thank you for contributing!
