### ISSUE TITLE
timewarp/time-lapse support. was: Unable to find audio stream in ffprobe output

### ISSUE THREAD

**Issue by Zebradil** [time4tea/gopro-dashboard-overlay#35]
I'm getting the following error (below) while trying to process a video without an audio stream. Such videos are produced, for example, with GoPro's "time-wrap" mode.

```
./venv/bin/gopro-dashboard.py --gpx ../100GOPRO/2022-05-28-083827-ELEMNT\ BCA8-120-0.gpx ../100GOPRO/2022-05-28_ride.mp4 ../100GOPRO/2022-05-28_ride-overlay.mp4
Traceback (most recent call last):
  File "/home/zebradil/archive/tmp/tools/./venv/bin/gopro-dashboard.py", line 84, in <module>
    stream_info = find_streams(input_file)
  File "/home/zebradil/archive/tmp/tools/venv/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 107, in find_streams
    audio = first_and_only("audio stream", streams, audio_selector)
  File "/home/zebradil/archive/tmp/tools/venv/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 97, in first_and_only
    raise IOError(f"Unable to find {what} in ffprobe output")
OSError: Unable to find audio stream in ffprobe output
```

**Comment by time4tea** [comment]
Thanks for this. Interesting! I've never used/seen this mode. I guess we don't actually need to know the audio stream to create overlays, only when creating splits/joins. Thanks for reporting, I'll take a look.

**Comment by time4tea** [comment]
TBH - I've no idea how the code will support "non-realtime" feamerates. Will just have to try it and see.

**Comment by time4tea** [comment]
Relabled as enhancement, to support additional video mode

**Comment by time4tea** [comment]
I've been looking at time-warp and time-lapse modes a bit. It looks like the gopro example software doesn't parse time-lapse videos properly either so getting the timing right might be a bit tricky (i wouldn't have something to compare against)

https://github.com/gopro/gpmf-parser/issues/159

**Comment by IbnGit** [comment]
I've been trying to make the code work with my gopro time lapse video for about a year.  

Your latest enhancements on timestamps are a huge leap forward. I'm a novice with python in that I can modify existing code, but not create new from scratch. I've fixed the audio stream issue my own way and I just saw you've made some changes to ffmpeg.py which will fix the issue more elegantly.

When I've got past this, I subsequently struggle with two other issues:

1. The stepper is a fixed time interval. While the GoPro time lapse theoretically does the same, there's a bit of drift in the time stamp.  It'd be ideal if the code would just use the time stamp as-is and avoid interpolating
2. The gradient chart seems to want to interpolate in entry.py and the code bombs out at the last frame. I don't know for certain, but I think this is for a the elevation chart in the window.

**Comment by time4tea** [comment]
Yeah, I think we have one part of the problem fixed now, which is understanding the timing of the gopro data. Using either of the timing mechanisms we can duplicate the gopro example timings. This is good. The next bit is to make sure that the way we step through that gopro data and emit frames lines up with the framerate of the video... Will have to figure out the best way to do that....
If a particular component is causing problems, it can be excluded by using `--exclude` or you can create your own layout very easily.

**Comment by time4tea** [comment]
When we get this right... there should be very little "drift" as this is how the frame stabilisation works inside the gopro.. it should be possible to align everything very accurately.. that's why I'm making changes here slowly :-)

**Comment by time4tea** [comment]
There is experimental support for timelapse/timewarp overlays in 0.57.0

**Comment by time4tea** [comment]
Nobody has said that it isn't, so I'll assume that it is fixed...

**Comment by Zebradil** [comment]
Hi @time4tea,

Thanks a lot for looking into this issue. Sorry, I wasn't able to participate in the discussion and testing before.

I've tested the latest version of gopro-dashboard from PyPi and the original error disappeared. I only had to remove timeout in `load_gpmd_from` function, but that's another thing and maybe something wrong on my side.

Thanks again for your effort!

**Comment by time4tea** [comment]
I dont quite follow what you mean by timeout?

**Comment by Zebradil** [comment]
It's `timeout` here: https://github.com/time4tea/gopro-dashboard-overlay/blob/main/gopro_overlay/ffmpeg.py#L182

This is the result of running with unmodified code (with the timeout set):

```
$ gopro-dashboard.py 2022-08-21_ride.mp4 2022-08-21_ride_overlay.mp4
Starting gopro-dashboard version 0.58.0
Input file has size Dimension(x=3840, y=2160)
Timer(loading timeseries - Called: 1, Total: 10.24270, Avg: 10.24270, Rate: 0.10)
Timer(program - Called: 1, Total: 10.24276, Avg: 10.24276, Rate: 0.10)
Traceback (most recent call last):
  File "/home/zebradil/archive/tmp/tools/venv/bin/gopro-dashboard.py", line 99, in <module>
    gopro_frame_meta = framemeta_from(
  File "/home/zebradil/archive/tmp/tools/venv/lib/python3.10/site-packages/gopro_overlay/framemeta.py", line 242, in framemeta_from
    gpmd_from = load_gpmd_from(filepath)
  File "/home/zebradil/archive/tmp/tools/venv/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 182, in load_gpmd_from
    result = run(cmd, capture_output=True, timeout=10)
  File "/home/zebradil/archive/tmp/tools/venv/lib/python3.10/site-packages/gopro_overlay/ffmpeg.py", line 20, in run
    return subprocess.run(cmd, check=True, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2004, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.10/subprocess.py", line 1196, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['ffmpeg', '-hide_banner', '-y', '-i', '2022-08-21_ride.mp4', '-codec', 'copy', '-map', '0:1', '-f', 'rawvideo', '-']' timed out after 10 seconds
```

Running `ffmpeg -hide_banner -y -i 2022-08-21_ride.mp4 -codec copy -map 0:1 -f rawvideo -` directly produces a lot of output into the stdout.

I can create a separate issue for that if it'll help.
