### ISSUE TITLE
km/h (kph) in custom layout

### ISSUE THREAD

**Issue by SteveClement** [time4tea/gopro-dashboard-overlay#41]
Currently only mph can be displayed. Having the option to define kmh would be nice :)

If I manage to understand the code, I will send a PR

Defining kph in the a custom layout seems to be enough, also, now after grepping for kph, I found the relevant docs.

[kph layout](https://github.com/time4tea/gopro-dashboard-overlay/tree/main/docs/xml/examples/04-metrics)

**Comment by time4tea** [comment]
Glad you were eventually able to find what you wanted in the docs. Suggestions on how to improve docs and/or user experience very much welcomed!
