### ISSUE TITLE
--layout-xml should imply --layout xml

### ISSUE THREAD

**Issue by osresearch** [time4tea/gopro-dashboard-overlay#47]
When `--layout-xml mycomponents.xml` is used with `gopro-dashboard.py`, it should imply `--layout xml`.  Otherwise the tool will use one of its default layouts and silently ignore the `--layout-xml` option.

**Comment by time4tea** [comment]
Yes this is a good idea.

**Comment by time4tea** [comment]
This has been released in 0.47.0
