### ISSUE TITLE
Feature request: add GPU acceleration to gopro-join.py

### ISSUE THREAD

**Issue by thereticle** [time4tea/gopro-dashboard-overlay#49]
gopro-join,py: I don't know if it's possible, but it would be useful to include the option to join files with GPU hardware acceleration (CUDA).

**Comment by time4tea** [comment]
Hiya - thanks for the suggestion. I'll be honest with you that pure performance things are not a huge priority. If you can give examples of a working ffmpeg command line that would be very helpful.

**Comment by time4tea** [comment]
Having looked at the command used to join the files - It looks like no encoding is used at all. The `-c copy` argument means that it is just a data stream copy, AFAICT. Unfortunately, video files are pretty big, so just copying data around can take a while. For example, my SD Card has a sustained read speed of about 50MB/sec - which means it takes 80 seconds just to read a 4GB segment, but a Samsung M2 drive might read at 3500Mb/s (480MB/s), so reading the same file in 9 seconds. For a 1 hour video - lets say 10x4GB files - just reading the data will take 13 minutes on an SD card. Similar things apply for write speeds, but writes are even slower.

**Comment by time4tea** [comment]
On my laptop I just tried  `gopro-join` for this use case. It took 2m30 to create an output file of 31.1GB, which works out at about 200MB/s.
