### ISSUE TITLE
Video size not dynamic based on input

### ISSUE THREAD

**Issue by fahrsoft** [time4tea/gopro-dashboard-overlay#5]
If the recorded video is anything other than 1920x1080, the overlay is not sized to match, so the right-side items are closer to the center of the screen with a larger format recording.

**Comment by time4tea** [comment]
There is now the ability to make custom layouts, which could have different placements for components. You could copy file the default-1080.xml and use `--layout xml --layout-xml <filename> ` to reference it. I will get around to making a version for 4k video, but that should work in the meantime.
The default-1080.xml file is here: https://github.com/time4tea/gopro-dashboard-overlay/blob/main/gopro_overlay/layouts/default-1080.xml

**Comment by time4tea** [comment]
This is mostly fixed in 0.21.0. Now support for 1920x1080 and 3840x2160.  You can force a specific overlay size by passing in "--overlay-size"
