### ISSUE TITLE
Timewarp overlay runs at wrong speed?

### ISSUE THREAD

**Issue by osresearch** [time4tea/gopro-dashboard-overlay#50]
I tried adding an overlay to a timewarp video ("Auto", which seems to be a 5-6x speedup) and the clock/map displays seem to run at the wrong speed.  They appear to be advancing in realtime, rather than tracking with the timestamps and position in the video.

**Comment by time4tea** [comment]
Hi, yeah time warp and time lapse don't work at the moment. This is also being tracked in #35
