### ISSUE TITLE
Improve how map is placed over the video

### ISSUE THREAD

**Issue by ptanov** [time4tea/gopro-dashboard-overlay#53]
It can be improved if some alpha fade out is present (e.g. like in <https://www.youtube.com/watch?v=3STZiAUG8e8>).
It will be best if alpha fade out is a feature of the `frame` so it can be used for other components, e.g. `gradient_chart`.
It should also support corner radius (`cr`) and opacity attributes if present.
User should be able to define how many pixels should be used for the fading.

**Comment by time4tea** [comment]
This was fixed with submitted PR
