### ISSUE TITLE
Interactive command line

### ISSUE THREAD

**Issue by julesgraus** [time4tea/gopro-dashboard-overlay#61]
Hey Guys,

I love this tool! I'm not good at python, and I wanted a command line tool that guides you through the process of generating a video with those overlays. I quickly scripted something, but it is a nodejs script. Maybe there is someone who could build it in python too! But in the mean time I'll be using my own. You are allowed to include it in this project if you would like to:

https://github.com/julesgraus/interactiveGoProDashboardTool

But if you do, you may need to put in some more work to have a user setup all command line arguments I guess. Now it was just build for my purposes only.

Kind regards and keep up the good work!

**Comment by time4tea** [comment]
Thanks for showing this! - It is really interesting to understand a bit more about the needs of people using the software, and the things that they are doing with it.

I'll put a link to it on the front page.

**Comment by time4tea** [comment]
Oh! - and also thank you for your kind words!
