### ISSUE TITLE
Feature request: allow rendering an overlay only video from GPX in an RGBA format

### ISSUE THREAD

**Issue by michaelochs** [time4tea/gopro-dashboard-overlay#64]
This project is really awesome but I think requiring GoPro footage is really limiting its potential. There are tons of other devices that generate GPS tracks and allow for exporting them as GPX or KML. I think it would be extremely beneficial if it was possible to use this tool to just give it a GPX file and then have it output a video file in a given resolution with RGBA, so with an alpha channel.

That way that video can then be used as an overlay over any kind of input. More importantly it can be used with Multicam clips in tools like Final Cut Pro. So you can have multiple camera angles but all or some of them would be showing the same overlay data.

**Comment by time4tea** [comment]
hiya - thanks for your interest. This was previously raised in #36 - the feature isn't currently planned, but I'm not dead set against it. Most of the bits that are needed are there - there is a way to read GPX files, and a way to output "only" the overlay. 
Maybe I should take another look - perhaps its not a huge amount of work.
The main problem i see is syncing the generated file with a recording from some other source. Quite a lot of effort is spent in this code to match up the rendered frame with the exact video frame, and to be honest its probably still not exact. I can imagine that simply outputting a 30fps video would drift over a longer ride (although, this is guesswork).
I hadn't considered using an external editing program to do the actual overlay, and this would alleviate my other concern of syncing the start of the ride with the start of the video - this would have to be done manually in the external editing program.

**Comment by time4tea** [comment]
I thought perhaps worth chatting about this in #66

**Comment by michaelochs** [comment]
Thanks. I commented there.

**Comment by ptanov** [comment]
Hope that this will solve the problem: <https://github.com/time4tea/gopro-dashboard-overlay/blob/77f0a66b7223bf59750420d24b1b33646d07f62d/docs/bin/README.md#:~:text=Create%20a%20movie%20with%20alpha%20channel%2C%20using%20only%20GPX%20file%2C%20without%20video%20from%20GoPro>

codec with alpha support should be used

**Comment by time4tea** [comment]
GitHub magically closed this - not sure its "closed" yet.
