### ISSUE TITLE
GoPro to GPX file including accelerometer, gyro, etc.

### ISSUE THREAD

**Issue by christian-nils** [time4tea/gopro-dashboard-overlay#71]
Hello!

Thank you very much for this project.

Are the GoPro data, such as acceleration and angular speeds, extracted in the GPX file when using `gopro-to-gpx.py` ?

------
Since I could not make it out of the box. I added some lines to `framemeta_to_gpx.framemeta_to_gpx()` to add these data to the TrackPoint as extensions.

```python
def framemeta_to_gpx(fm: FrameMeta, step: timedelta = timedelta(seconds=0)):
    gpx = gpxpy.gpx.GPX()

    # Add TrackPointExtension namespace
    gpx.nsmap["gp2d"] = "./xmlschemas/GoProToDash/v1"

    gpx_track = gpxpy.gpx.GPXTrack()
    gpx.tracks.append(gpx_track)

    gpx_segment = gpxpy.gpx.GPXTrackSegment()
    gpx_track.segments.append(gpx_segment)

    last_dt = datetime.datetime(year=1900, month=1, day=1, tzinfo=datetime.timezone.utc)

    for entry in fm.items():
        entry_dt = entry.dt

        if entry_dt > last_dt + step:
            last_dt = entry_dt
            gpx_point = gpxpy.gpx.GPXTrackPoint(
                    time=entry_dt,
                    latitude=entry.point.lat,
                    longitude=entry.point.lon,
                    speed=entry.speed.to('m/s').magnitude,
                    elevation=entry.alt.to("m").magnitude)
            gpx_segment.points.append(gpx_point)
            extensions = ElementTree.fromstring(f"""<gp2d:TrackPointExtension xmlns:gp2d="{gpx.nsmap["gp2d"]}">
            <gp2d:accl_x>{entry.accl.x.magnitude}</gp2d:accl_x>
            <gp2d:accl_y>{entry.accl.y.magnitude}</gp2d:accl_y>
            <gp2d:accl_z>{entry.accl.z.magnitude}</gp2d:accl_z>
            <gp2d:gyro_x>{entry.gyro.x.magnitude}</gp2d:gyro_x>
            <gp2d:gyro_y>{entry.gyro.y.magnitude}</gp2d:gyro_y>
            <gp2d:gyro_z>{entry.gyro.z.magnitude}</gp2d:gyro_z>
            </gp2d:TrackPointExtension>""")
            gpx_point.extensions.append(extensions)

    return gpx
```

I am not really proficient with GPX file format, so this may be completely unnecessary (or not the right way).

Note that I created a method `gyro_framemeta` using `accl_framemeta` as model to extract the data from the gyroscope.

**Comment by time4tea** [comment]
Hi - Thanks for this! - I'll take a closer look. I'm curious though - what software will you use to parse the generated files? There doesn't seem to be a "well-known" gpx extension for acceleration and gyro data - the only documented one I could find is for garmin https://github.com/Rasbats/opencpn_schema/blob/main/GpxExtensionsv3.xsd ... I don't mind adding this, but it would be good to understand a little more about how it will be consumed...

**Comment by christian-nils** [comment]
Thanks for the quick reply! Yeah, maybe it does not make much sense. My idea was to extract the data from the GoPro into a data file without the video frame. Then I wanted to add the attitude information (yaw, pitch, and roll) to the GPX file with an external script and add the overlay to the video. It could be the original GoPro video or another video file that was capture at the same time.

This might just not make sense :D. I wanted just to confirm that there was no option to save those GoPro timeseries directly into the GPX file with the gopro-to-gpx.py script.

**Comment by time4tea** [comment]
Hmm.. if you were starting with a GoPro video - you can create widgets already for the acceleration - there are some examples here: https://github.com/time4tea/gopro-dashboard-overlay/blob/main/docs/xml/examples/07-bar/README.md - but you are right that you don't seem to be able to draw widgets for the gyro readings at the moment... this was something that I mean to add, but seem to have forgotten to do. 
If i added the capability to draw overlay widgets using the gyro readings, would that solve your problem?

**Comment by christian-nils** [comment]
Hi again! I really appreciate your help!

I was able to use the overlay widgets to display the angular velocity, I added the gyro values to the `framemeta` object. To give more details about what I want to achieve, here is some context:

We have an instrumented powered two-wheeler were we collect data from 2 IMUs, from 4 ToF sensors, and 1 potentiometer, together with a GoPro Hero 5. We can determine from these sensors: pitch, yaw, and roll angles as well as the steering angle. The idea was to overlay the GoPro video with those processed data together with the raw data from the GoPro, and potentially other sensors.

I was thinking adding those processed data as `extensions` to the GPX file (via an external script) so we could merge data from the GoPro + the external sensors and create the dashboard overlay.

I wanted to extract the raw IMU data from the GoPro in the GPX file so I could just work with one data file in my external script. 

I am working now on adapting `gpx_to_timeseries` to account for my custom variables, I think I'll figure out :)

Regarding your point about adding the gyro readings to your library, I would definitively that could be useful for other applications too !

Thanks again, have a great day,

/CN

**Comment by time4tea** [comment]
Oh, I'm definitely not saying we shouldn't do something like this, but just trying to understand more about your use case... the more I understand the more I can make potentially useful suggestions.

**Comment by christian-nils** [comment]
I understand, I am grateful for it! What would be your approach to add external data ?

**Comment by time4tea** [comment]
Would it be ok to move this conversation to a discussion? I'll create one in the discussions #75
