### ISSUE TITLE
Create dockerhub image.

### ISSUE THREAD

**Issue by time4tea** [time4tea/gopro-dashboard-overlay#73]
Create a dockerhub image so that people can use the software without installing all the dependencies.

**Comment by time4tea** [comment]
Discussing in #72

**Comment by GitFun4All** [comment]
Hi again, I've uploaded the images to docker hub to make life easier (hopefully). I've tested it on Mac, X86 and (M1/M2) aarch64 and so far both work well for me.

Thanks again for the project, it's really nice!!

**Comment by time4tea** [comment]
Docker image is now created at https://hub.docker.com/r/overlaydash/gopro-dashboard-overlay

Thanks for your suggestion, and for example Dockerfile . After a bit of thought, I thought it might be more generally applicable if it just ran whatever program you specified, rather than having some wrapper script. This was it can be scripted externally, and also additional programs can be included into the docker image without changing the entrypoint script.

**Comment by time4tea** [comment]
I've not implemented the ARM docker image quite yet. This will come soon.

**Comment by GitFun4All** [comment]
I liked the look of your images and the clean compline only versions.
With the aarm64 based docker image I found dockx cross compiles well.
I’ve tested it so far on Mac intel + Apple M1,2 and armv7 raspberry pi (although too slow to be practical) and amd64.

**Comment by time4tea** [comment]
Thanks! I had a bit of trouble with the aarch64 version. It builds when I run exactly the commands in a shell running inside an emulator, but when I run the build with docker buildx I get an error running meson. Not quite sure what's happening there.

**Comment by time4tea** [comment]
Are you building the aarch64 on an arm or an amd64? What's the build command line you use? Tha ks!!!

**Comment by GitFun4All** [comment]
I’m building the arm image on a ‘Apple silicon’ Mac and the amd64 on an intel one. I also had a few weird issues trying to get all architectures to work on the intel Mac, though if I use the aarch64 one dockx seems to work for everything including arm7 ( raspberry pi etc) To be honest I’m mainly interested in getting full speed out of the none intel Mac, not sure how useful the arm7xx builds are as they are usually more modest devices…. I haven’t tried your updated docker files but will give them a go to see if one file really can suit all.Cheers!On 8 Nov 2022, at 09:04, James Richardson ***@***.***> wrote:﻿
Are you building the aarch64 on an arm or an amd64? What's the build command line you use? Tha ks!!!

**Comment by time4tea** [comment]
Sounds like people are using the Docker image.. so will close this as fixed.
