### ISSUE TITLE
gpx2video software

### ISSUE THREAD

**Issue by progweb** [time4tea/gopro-dashboard-overlay#8]
Hi, I searched solution to render video with overlay on Linux. Finally, I have started to write my software tool gpx2video :

https://github.com/progweb/gpx2video

I have just found your great project, I'm going to add a section about alternatives solutions.

**Comment by time4tea** [comment]
Hey! Thank you! Nice work 💯! It's great to see more people making this type of software. I'll update with a link back to you also.

I think you have got some great ideas there!
