### ISSUE TITLE
Feature Request: Data point interpolation (GPX timeseries import)

### ISSUE THREAD

**Issue by 0x10** [time4tea/gopro-dashboard-overlay#89]
First of: THANK YOU for your awesome tool. 
I have a feature request. I may help you implement it, if I get the theory behind it correct and if that feature isn't achievable otherwise.

I work with fit or gpx files from Garmin devices and they record data typically in 1s trackpoints / samples. If used the resulting data overlay will only be updating in this 1s interval which results in a "not so smooth" visual impression.
As far as I can guess (as this isn't documented), Garmin VIRB Edit will interpolate the data accordingly to fill the gaps and make a smooth transition from one data point to another. But this tool isn't available FOSS and it doesn't allow export the overlay interpolated data (it does it only for its own video encoding).

This kind of interpolation would be my feature request.
I identified the place where this could be added as a separate function which is called if the caller has requested it (this option could then be a cmd line argument): 
https://github.com/time4tea/gopro-dashboard-overlay/blob/d64005f6514a5ca48fd8cc14e0599eff543f90b3/gopro_overlay/framemeta_gpx.py#L74

The implementation I would suggest would take the simplest form using linear interpolation and firstly skip interpolation of GPS positions (the added data points would share the same GPS position).

GPS interpolation could be achieved later using one of the already existing interpolation libraries, e.g. https://github.com/remisalmon/gpx-interpolate

fit file (csv converted) sample:
Data,3,record,timestamp,"1042549234",s,position_lat,"447881285",semicircles,position_long,"-923817563",semicircles,distance,"10.49",m,heart_rate,"131",bpm,altitude,"51.60000000000002",m,speed,"9.378",m/s,power,"158",watts,cadence,"85",rpm,enhanced_altitude,"51.60000000000002",m,enhanced_speed,"9.378",m/s,,,,,,,,,,,,,
Data,3,record,timestamp,"1042549235",s,position_lat,"447880422",semicircles,position_long,"-923818294",semicircles,distance,"20.18",m,heart_rate,"131",bpm,altitude,"51.60000000000002",m,speed,"9.436",m/s,power,"159",watts,cadence,"84",rpm,enhanced_altitude,"51.60000000000002",m,enhanced_speed,"9.436",m/s,,,,,,,,,,,,,
D

**Comment by time4tea** [comment]
Hi thanks for the nice comments! - Yes this is something that the code used to do, actually. I think it was missing a test, and the behaviour changed... It should be easy enough to do.

**Comment by 0x10** [comment]
Thanks for your rapid reply. Do you mean with "used to do", that there is already an implementation? May you have a link within the code? Or is the implementation gone lost, due to some changes?

**Comment by time4tea** [comment]
Hi, the changes are already made, but I have not had a chance to make a release, which I will do soon, today or tomorrow.

**Comment by time4tea** [comment]
https://github.com/time4tea/gopro-dashboard-overlay/commit/cdd030c5926c7de1b29cbedc92a14fd4c60dc7c9

**Comment by 0x10** [comment]
wow! Thank you. I'll test it!

**Comment by 0x10** [comment]
Works like a charm. THANK YOU.

**Comment by time4tea** [comment]
This functionality is in 0.77.0,which in on pypi/dockerhub now. Thanks for rasing it.
