### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by KyleGW** [time4tea/gopro-dashboard-overlay#9]
![gopro-dashboard-overlay error](https://user-images.githubusercontent.com/9725098/151293967-8d366ed5-bd58-4251-8256-8cd188a03818.jpg)

**Comment by KyleGW** [comment]
![ffprobe of test file for gopro-dashboard-overlay](https://user-images.githubusercontent.com/9725098/151294551-a5b1c5f5-4915-439e-a884-1a4cd2ad0e4e.jpg)

**Comment by time4tea** [comment]
Hi. Thanks for taking the time to post a bug. 

You don't need to extract the gpx data first from the video, the dashboard program can read it directly from the video file.
The "--gpx" option is there just in case you have additional files, say from a bike GPS, that you want to merge with the data from the gopro.
If you try running the program again, without the --gpx option, you may have more luck.
I'll see if the instructions can be improved so this is clearer.

**Comment by KyleGW** [comment]
Also quick FYI, this is working for me on Windows 11 using Ubuntu on Windows Subsystem for Linux (WSL) which is a Windows feature I could enable after turning on virtualization in BIOS and enabling Hyper-V.

**Comment by time4tea** [comment]
Great. Maybe if you could let me know what are the top few things you'd like to do with the program, I could take a look at how easy they might be. Please annotate it from absolutely essential to maybe possibly useful...

**Comment by time4tea** [comment]
Re WSL, that is super interesting, thank you!

**Comment by KyleGW** [comment]
annd I just realized the top map is a moving map. awesome! I need to try out the other map types and also figure out how to adjust the map scale. I am using this for flying and there were no roads around, so it was just showing me grey box with a blue dot in the middle using OSM.

**Comment by time4tea** [comment]
I've published a new version. It solves 1,2 & 3 on your list I think. I'll close this issue for now, as I the initial reported defect has been addressed.
