### ISSUE TITLE
gopro-rename AttributeError

### ISSUE THREAD

**Issue by matzeruegge** [time4tea/gopro-dashboard-overlay#93]
gopro-rename.py --dirs . 
gives AttributeError: 'str' object has no attribute 'name'

ls g* 
g0020520.jpg  gh010531.mp4  gh010538.mp4  gh010547.mp4	gopr0509.jpg  gopr0514.jpg  gopr0523.jpg  gopr0529.jpg	gopr0539.jpg  gopr0549.jpg
gh010512.mp4  gh010533.mp4  gh010540.mp4  gopr0506.jpg	gopr0510.jpg  gopr0516.jpg  gopr0526.jpg  gopr0532.jpg	gopr0541.jpg
gh010524.mp4  gh010536.mp4  gh010543.mp4  gopr0507.jpg	gopr0511.jpg  gopr0517.jpg  gopr0527.jpg  gopr0534.jpg	gopr0545.jpg
gh010525.mp4  gh010537.mp4  gh010544.mp4  gopr0508.jpg	gopr0513.jpg  gopr0518.jpg  gopr0528.jpg  gopr0535.jpg	gopr0548.jpg

**Comment by time4tea** [comment]
Should be fixed in v0.81.0
