### ISSUE TITLE
error during container init

### ISSUE THREAD

**Issue by shahargli** [time4tea/gopro-dashboard-overlay#97]
Hello,

While running gopro-dashboard.py via docker on windows 10, I get the following error:
docker run -v ./ overlaydash/gopro-dashboard-overlay:0.64.0 gopro-dashboard.py

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown.

Any idea why?

**Comment by time4tea** [comment]
Hiya - yes - I think there is an error with your docker command.

Map the folder with the files in to `/work`, as per the example,

`docker run -v $(pwd):/work overlaydash/gopro-dashboard-overlay:0.81.0 gopro-dashboard.py`

I noticed you used version `0.64.0`, which was given in the example, but is actually quite old now - it was an example - the latest versions are shown at the top of the page. I realise this could be confusing, so will try to update the latest version number in the docs.

Thanks for raising an issue - hope that's useful.

**Comment by shahargli** [comment]
working now!
thanks much for the promt response
